- apps/web-calc-featured/src/assets/style/elements/_AgentsSlider.scss
- apps/web-calc-featured/src/components/elements/agentsSlider.jsx
- apps/web-calc/src/assets/style/elements/_AgentsSlider.scss
- apps/web-calc/src/components/elements/agentsSlider.jsx
Integrating native LA form instead of php one
Close issue https://github.com/QualityUnit/web-issues/issues/375
> [375] Integrating native LA form instead of php one

- assets/scripts/app/custom_lazyload.js
- assets/styles/app.scss
- assets/styles/common/_elementor.scss
- assets/styles/components/_Block.scss
- assets/styles/components/_BlockSwitcher.scss
- assets/styles/components/_Boxes.scss
- assets/styles/components/_FeaturesTable-New.scss
- assets/styles/elements/_Typography.scss
- functions/lazy-load.php
Implementing Call center redesign CSS changes, support for srcset images lazyload
> [284] Callcenter redesign

- assets/styles/components/_FeaturesTable-New.scss
> [284] Minor fixes to Features table

- assets/styles/components/IconTabs.scss
- assets/styles/components/_Block.scss
- assets/styles/components/_BlockPricing.scss
- assets/styles/components/_BlockVideo.scss
Small livechat design changes
Close Issue https://github.com/QualityUnit/web-issues/issues/283
> [283] Small livechat design changes

- assets/scripts/static/crm.js
**What was changed?**
Added tracking code for G2.com
**Checklist**
Close QualityUnit/web-issues#381
> [381] Added tracking code for G2.com

- assets/styles/components/_BlockLearnMore.scss
- functions/content-filters.php
Added content formatting for long content in Learn More block
**Checklist**
Close QualityUnit/la-marketing#2026
> [2026] Added content formatting for long content in Learn More block

- assets/styles/components/_BlockQuote.scss
- assets/styles/layouts/_Post.scss
2 small fixes
**Checklist**
Close QualityUnit/web-issues#378
Close QualityUnit/web-issues#385
> [378] 2 small fixes

- lib/metaboxes/directory.php
- templates/content-single-ms_directory.php
Add Support for 15 FAQ Items in Directory
**Checklist**
Close QualityUnit/web-issues#394
> [394] Add Support for 15 FAQ Items in Directory

- lib/shortcodes/similar-sources.php
Update Related Resources
**Checklist**
> Update Related Resources

- CHANGELOG.md
- functions.php
- style.css
Bump version to 1.0.2
**Checklist**
> Bump version to 1.0.2

- assets/styles/common/_elementor.scss
- assets/styles/components/_BlockSwitcher.scss
- assets/styles/components/_BlockVideo.scss
- assets/styles/components/_HorizontalTabs.scss
Mobile and tablet fixes
**Checklist**
Close QualityUnit/web-issues#390
> [390] Mobile and tablet fixes

- assets/styles/components/_HeroHeadlineHome.scss
Woman Mask image fix
**Checklist**
Close QualityUnit/web-issues#388
> [388] Woman Mask image fix

- assets/styles/pages/About.scss
Fixing About  us milestones
**Checklist**
Close QualityUnit/web-issues#399
> [399] Fixing About  us milestones

- assets/styles/components/_BlogShare.scss
- assets/styles/layouts/_BlogPost.scss
Blog post fixes
**Checklist**
Close QualityUnit/web-issues#398
> [398] Blog post fixes

- lib/widgets/qu-checklists/checklists.php
- lib/widgets/qu-checklists/layouts/checklist-item.php
- lib/widgets/qu-checklists/src/edit.js
- lib/widgets/qu-checklists/src/scss/editor.scss
Schema.org additional fields
**Checklist**
Close QualityUnit/web-issues#419
> [419] Schema.org additional fields

- assets/styles/components/_FeaturesTable-New.scss
Small changes to features table
**Checklist**
Close QualityUnit/web-issues#412
> [412] Small changes to features table

- assets/images/icon-search_new_v2.svg
- assets/styles/elements/_SearchField.scss
- templates/content-archive-ms_academy.php
- templates/content-archive-ms_checklists.php
- templates/content-archive-ms_features.php
- templates/content-archive-ms_integrations.php
- templates/content-archive-ms_templates.php
> New search icon

- assets/scripts/static/crm-free_cr.js
- assets/scripts/static/crm-free_jp.js
- assets/scripts/static/crm-free_no.js
- assets/scripts/static/crm_cr.js
- assets/scripts/static/crm_jp.js
- assets/scripts/static/crm_no.js
Trial messages translations
**Checklist**
**Checklist**
Close QualityUnit/web-issues#299
> [299] Trial messages translations

- assets/styles/components/_BlockDiscover.scss
- assets/styles/elements/_Button.scss
Fix for new BlockDiscover buttons
**Checklist**
Close QualityUnit/web-issues#421
> [421] Fix for new BlockDiscover buttons

- assets/scripts/app/sidebarFloating.js
- assets/styles/components/_CategorySidebar.scss
Fix for floating Category sidebar
**Checklist**
Close QualityUnit/web-issues#446
> [446] Fix for floating Category sidebar

- assets/scripts/app/sidebarFloating.js
Check for element presense fix
**Checklist**
Close QualityUnit/web-issues#446
> [446] Check for element presense fix

- assets/scripts/app/sidebarFloating.js
Fix for JS in category sidebar
**Checklist**
> Fix for JS in category sidebar

- elementor.php
- lib/widgets/qu-checklists/checklists.php
- lib/widgets/qu-checklists/layouts/checklist-item.php
- lib/widgets/qu-checklists/package.json
- lib/widgets/qu-checklists/src/components/CheckListItem.js
- lib/widgets/qu-checklists/src/edit_checklistitem.js
- lib/widgets/qu-checklists/src/scss/editor.scss
Include image schema.org microdata – via Media library or automatic fallback to checklist content or post header image
**Checklist**
Close QualityUnit/web-issues#451
> [451] Include image schema.org microdata

- CHANGELOG.md
- functions.php
- style.css
bump version to 1.0.6
**Checklist**
> feat: bump version to 1.0.6

- lib/shortcodes/signup-form-free.php
- lib/shortcodes/signup-form.php
- lib/shortcodes/signup-sidebar.php
Trial send emails classification
Go to http://liveagent.local/trial and attempt to send a form. Ask @pcupra (Peter Cupra) if values for secondary mail were send.
**Checklist**
Close QualityUnit/web-issues#485
> [485] feat: trial send emails classification

- apps/web-calc-featured/src/components/elements/agentsSlider.jsx
- apps/web-calc-featured/src/components/layouts/finalResults.jsx
- lib/shortcodes/web-calc-featured.php
fix: number of agents price
go to liveagent.local/call-center-software/ (or www.liveagent.com/call-center-software/ after deployed) and scroll down to Web calc. Price shoud correctly start at $49
**Checklist**
Close QualityUnit/web-issues#491
> [491] fix: number of agents price

- base.php
- lib/shortcodes/signup-form-free.php
- lib/shortcodes/signup-form.php
- lib/shortcodes/signup-sidebar.php
fix: wrong sending event
**Checklist**
Close QualityUnit/web-issues#485
> [485] fix: wrong sending event

- CHANGELOG.md
- functions.php
- style.css
feat: bump version to 1.0.9
**Checklist**
> feat: bump version to 1.0.9

- .github/dependabot.yml
- change dependabot settings
**Checklist**
> chore: change dependabot settings

- base.php
Pap tracking with/without cookie
**Checklist**
Close QualityUnit/web-issues#500
> [500] fix: pap tracking with/without cookie

- apps/web-calc/src/components/elements/agentsSlider.jsx
Number of agents improperly calculated price
Go to http://liveagent.local/costs-calculator (or www.liveagent.com/costs-calculator once deployed), preset some LiveAgent competitors, some options and at the results chart page, try to move Agents slider. Prices should change accordingly. Please note that some of the competitors (like Bitrix) have fixed price in some cases
**Checklist**
Close QualityUnit/web-issues#467
> [467] fix: number of agents improperly calculated price

- assets/styles/elements/_Button.scss
- assets/styles/layouts/_Header.scss
Reduced margin on Demo button in main navigation.
**Checklist**
Close QualityUnit/web-issues#495
> [495] style: reduced margin on demo button

- apps/web-calc-featured/src/components/elements/chartBar.jsx
- apps/web-calc/src/components/elements/chartBar.jsx
removal of competitors links in webcalc
**Checklist**
Close QualityUnit/web-issues#499
> [499] fix: removal of competitors links in webcalc

- assets/styles/layouts/_Header.scss
Fixed hover effect on integration menu items
**Note**
Requires to add "button-more-integrations" class to more integrations menu item na WP
**Checklist**
Close QualityUnit/web-issues#492
> [492] style: fixed hover effect for integration menu items

- CHANGELOG.md
- functions.php
- style.css
bump version to 1.0.10
**Checklist**
> feat: bump version to 1.0.10

- CHANGELOG.md
- functions.php
- style.css
bump theme version to 1.0.11
**Checklist**
> chore: bump theme version to 1.0.11

- base.php
pap tracking script on cookie accept
Verify if tracking event is sent upon Cookie accept (in incognito) in Network panel of the browser without parameter mode=SC
**Checklist**
Close QualityUnit/web-issues#500
> [500] fix: tracking on cookie accept

- base.php
Reverts QualityUnit/liveagent-theme#200
> Revert "[500] fix: tracking on cookie accept"

- assets/styles/components/_BlockVideo.scss
Video position in video block on desktop
check video position on desktop resolutions
**Checklist**
Close QualityUnit/web-issues#502
> fix: video position in video block on desktop

- assets/styles/layouts/_BlogPost.scss
- base.php
- templates/content-single.php
Blog category fix for urls not closed properly after regex
**Checklist**
Close QualityUnit/web-issues#554
> [554] Blog category fix

- assets/scripts/app/sidebarFloating.js
- assets/styles/components/_CategorySidebar.scss
- assets/styles/pages/Category.scss
- category sidebar in PAP design (right padding set to 24px for scrollbar space)
- sidebar overflow and fix position disabled, when content height is small
- z-idex of category content and sidebar (newsletter button above mobile sidebar)
tested in common browsers in browserstack
please aproove css changes in "Category__container", "Category__sidebar" and "Category__content" 
**Checklist**
Close QualityUnit/web-issues#482
> [482] Replicate the Design of Feature's Sidebar Menu

- assets/images/arrow-right-orange.svg
- assets/styles/components/_BoxesStars.scss
Redesigned item element
Element can be found on [/use-case-scenarios/](http://liveagent.local/use-case-scenarios/)
**Checklist**
**Note**
After deployment is needed to add Learn more link for every item, which contains a link in elementor
Close QualityUnit/web-issues#536
> [2126] feat: redesign of item element

- assets/scripts/app/toggleVisibility.js
- assets/styles/components/_BlockSwitcher.scss
Automatic image switcher on block--switcher
Go to ie. http://liveagent.local/ticketing-software/ (or https://www.liveagent.com/ticketing-software/ after deployed) and check if „Lets chat“ element has automatic switching between images
**Checklist**
Close QualityUnit/web-issues#481
> [481] fix: automatic image switcher on block--switcher

- templates/content-single-ms_directory.php
changed title for trial sidebar on directory
**Checklist**
Close QualityUnit/web-issues#513
> [513] fix: changed title for trial sidebar on directory

- lib/custom-blocks/checklist-post-header-small.php
Fixed wrong condition in checklist post small header, conditionally removing enclosing div.
**Checklist**
Close QualityUnit/web-issues#583
> [583] fix: checklist condition

- CHANGELOG.md
- functions.php
- style.css
bump theme version to 1.0.13
**Checklist**
> chore: bump theme version to 1.0.13

- assets/scripts/app/toggleVisibility.js
changed condition of switcher querySelector
Test if all videos on page are clickable
**Checklist**
Close QualityUnit/web-issues#593
> [593] toggleVisibility js fix

- CHANGELOG.md
- functions.php
- style.css
bump theme version to 1.0.14
**Checklist**
> chore: bump theme version to 1.0.14

- assets/styles/components/_SignupSidebar.scss
- assets/styles/layouts/_Post.scss
"Signup__sidebar" shows only on desktop resolutions
test sidebar behavior on post pages
**Checklist**
Close QualityUnit/web-issues#581
> [581] Responsive behavior of sidebars on post pages

- assets/styles/components/_SimilarSources.scss
- templates/content-single-ms_checklists.php
Add related resources to checklists
E.g. [this URL](http://liveagent.local/checklists/starting-podcast-checklist/).
**Checklist**
Close QualityUnit/web-issues#596
> [596] feat: add related resources to checklists

- CHANGELOG.md
- functions.php
- style.css
bump theme version to 1.0.15
**Checklist**
> chore: bump theme version to 1.0.15

- templates/content-single-ms_directory.php
- templates/content-single-ms_glossary.php
- templates/content-single-ms_integrations.php
redefine translation string to allow translation
**Checklist**
Close QualityUnit/web-issues#562
> [562] feat: redefine translation string to allow translation

- lib/widgets/qu-howtos/src/scss/_editor-styles.scss
- lib/widgets/qu-howtos/src/scss/_howto.scss
- lib/widgets/qu-howtos/src/scss/editor.scss
- lib/widgets/qu-howtos/webpack.config.js
Howtos formatting with bullet lists
**Checklist**
Close QualityUnit/web-issues#610
> [610] fix: howtos formatting

- functions/content-filters-learn-more.php
Encoding in sidebar, php formatting
Go to https://www.liveagent.lv/tiessaistes-cata-programmatura/ and check if characters in sidebar in Learn More block at the bottom corresponds with titles in main content
**Checklist**
Close QualityUnit/web-issues#613
> [613] fix: encoding in sidebar, php formatting

- assets/styles/common/_elementor.scss
- assets/styles/pages/Directory.scss
- templates/content-single-ms_directory.php
Fixing missing url and safari hover
**Checklist**
Close QualityUnit/web-issues#595
> [595] fix: missing url and safari hover

- CHANGELOG.md
- assets/styles/pages/Directory.scss
- functions.php
- style.css
bump theme version to 1.0.16
**Checklist**
> chore: bump theme version to 1.0.16

- functions/content-filters.php
- functions/lazy-load-youtube-microdata.php
Rewriting regex for adding microdata to dom
Go to https://admin.liveagent.com/ticketing-software/ (once deployed) and check if two vertical videos have orange play button (What is a ticketing software? and  Ticketing system with intuitive UI).
Also, use inspector on image part of these elements and check if there is <div itemprop="video" … block for each of these video blocks
**Checklist**
> fix: rewriting regex for adding microdata to dom

- assets/scripts/custom/blogLazyLoad.js
fix: not working blog posts lazyload
**Checklist**
> fix: not working blog posts lazyload

- lib/shortcodes/block-pricing.php
Reworked pricing shortcode to for cycle. 
Check if pricing element still displays correctly, can be found on e.g. [/ticketing-software](http://liveagent.local/ticketing-software).
**Checklist**
> feat: reworked php to a cycle

- functions/content-filters.php
refactor codingStandardsIgnore block in elementor_pros_cons function
**Checklist**
> refactor: codingStandardsIgnore block removed in content filter

- CHANGELOG.md
- functions.php
- style.css
bump theme version to 1.0.17
**Checklist**
> chore: bump theme version to 1.0.17

- CHANGELOG.md
- functions.php
- style.css
bump theme version to 1.0.18
**Checklist**
> chore: bump theme version to 1.0.18

- lib/shortcodes/block-pricing.php
Fixing wrong enclosing in block pricing
**Checklist**
> fix: block pricing closing div

- CHANGELOG.md
- functions.php
- style.css
bump theme version to 1.0.20
**Checklist**
> chore: bump theme version to 1.0.20

- assets/styles/components/_TrialBanner.scss
Redesigned AD element
Go to [this](http://liveagent.local/industry/) page, scroll down to this element
and check if everything is ok.
**Checklist**
Close QualityUnit/web-issues#626
> [626] style: redesigned ad element

- assets/styles/components/_BlockPricing.scss
- lib/shortcodes/block-pricing.php
Fixes for pricing element in reference to [feedback](https://www.figma.com/file/xt1LfCwePFyS0CoVgWQZOx/LA-WEB-RfD---Knowledge-base?node-id=202%3A432)
Go to [this](http://liveagent.local/social-media-customer-service/) page, scroll down a little and check if everything is fixed according to Laci's feedback.
**Checklist**
> fix: fixes for pricing element

- templates/header.php
I have developed new demo button for navigation bar, fully responsible, styled and functional.
**Checklist**
**After merging**
Close QualityUnit/web-issues#625
> feat(web): add demo button

- assets/styles/components/_BlockStartups.scss
Urls to images for startups fix
**Checklist**
Close QualityUnit/web-issues#540
> [540] fix: urls to images for startups

- assets/styles/components/_CategoryItem.scss
Position on Read More button was set from absolute to static
Check position of Read More button and responsive behavior
**Checklist**
Close QualityUnit/web-issues#621
> [621] Read More button visible on mobile

- assets/styles/layouts/_Post.scss
Fixed layout of post buttons
Test layout of post buttons on mobile and desktop
**Checklist**
Close QualityUnit/web-issues#619
> [619] Post Buttons margins on mobile

- CHANGELOG.md
- functions.php
- style.css
bump theme version to 1.0.21
**Checklist**
> chore: bump theme version to 1.0.21

- CHANGELOG.md
- assets/scripts/custom/blogLazyLoad.js
- base.php
- functions.php
- functions/content-filters-functions.php
- functions/content-filters.php
- style.css
- add wp body open tag
- deactivate lazy load theme features
- bump theme version to 1.0.22
**Checklist**
> feat: changes before urlslab plugin update

- assets/scripts/app/toggleVisibility.js
- assets/styles/components/_BlockSwitcher.scss
Addin support for switching text in Switch element.
Auto toggle commented out for now
To be edited on:
https://www.liveagent.com/ticketing-software/
https://www.liveagent.com/live-chat-software/
https://www.liveagent.com/call-center-software/
https://www.liveagent.com/social-media-customer-service/
https://www.liveagent.com/knowledge-base-software/
**Checklist**
Close QualityUnit/web-issues#657
> [657] switch element switch text

- assets/styles/components/_ExtraFaq.scss
Change requested in help desk page redesign
**Checklist**
> style: adjusted margin under h1 in faq

- assets/styles/layouts/_Header.scss
Extended main menu padding fix for next languages.
Check header look in all languages
**Checklist**
Close QualityUnit/web-issues#711
> [711] Main Nav width in some languages

- assets/styles/components/_BlockDiscover.scss
- assets/styles/components/_ExtraFaq.scss
Fixed styles for URLslab generated links
Check styles of URLslab generated links
**Checklist**
Close QualityUnit/web-issues#695
> [695] URLslab generated links styles

- CHANGELOG.md
- assets/scripts/custom/blogLazyLoad.js
- functions.php
- style.css
bump theme version to 1.0.23
**Checklist**
> chore: bump theme version to 1.0.23

- templates/content-archive-ms_checklists.php
Changed search items classes on archive-ms_checklists pages
Check search functionality on checklists page
**Checklist**
Close QualityUnit/web-issues#685
> [685] Search field in the checklist section

- CHANGELOG.md
- assets/styles/components/_BlockStartups.scss
- functions.php
- style.css
Fix for startups formatting
**Checklist**
Close QualityUnit/web-issues#540
> [540] fix: startups

- assets/styles/common/_variables.scss
- assets/styles/components/_Block.scss
- assets/styles/components/_BlockChannels.scss
- assets/styles/components/_BlockPoints.scss
- assets/styles/components/_BlockSolutions.scss
- assets/styles/components/_Boxes.scss
- assets/styles/components/_Faq.scss
- assets/styles/components/_HeroBanner.scss
- assets/styles/components/_HorizontalTabs.scss
- assets/styles/components/_Reviews.scss
- assets/styles/components/_Text.scss
- assets/styles/components/_VerticalTabs.scss
Changed spaces between blocks from 100px to 150px on desktop
Check spaces between block across site
**Checklist**
Close QualityUnit/web-issues#674
> [674] New sizes of block spaces

- assets/styles/common/_variables.scss
- assets/styles/elements/_Checklist.scss
Default element margin changed from 15px to 20px
Check margins of elements across site
**Checklist**
Close QualityUnit/web-issues#673
> [673] Elements margin changed

- lib/shortcodes/block-quote.php
Fixed typo in tag of blockquote shortcode
Check blockquote element
**Checklist**
Close QualityUnit/web-issues#656
> [656] Typo in tag of blockquote shortcode

- functions.php
- functions/lazy-load-youtube-microdata.php
Removing of. YT Video Schema
**Checklist**
> Remove YouTube Video schema.org

- CHANGELOG.md
- functions.php
- style.css
- update theme to 1.0.26
**Checklist**
> chore: update theme to 1.0.26

- assets/styles/pages/About.scss
- lib/widgets/qu-checklists/yarn.lock
Sidebar is more compact on mobile.
Gap between header and sidebar was fixed on mobile.
Sidebar's left spacing was fixed.
Check about sidebar responsive look.
**Checklist**
Close QualityUnit/web-issues#620
> [620] Sidebar on  About pages

- CHANGELOG.md
- functions.php
- style.css
bump theme version to 1.0.27
**Checklist**
> chore: bump theme version to 1.0.27

- CHANGELOG.md
- functions.php
- style.css
bump theme version to 1.0.28
**Checklist**
> chore: bump theme version to 1.0.28

- functions/content-filters.php
fixing yoast schema urls
**Checklist**
Close QualityUnit/web-issues#734
> [734] fix: fixing yoast schema urls

- assets/styles/layouts/_Header.scss
- functions/content-filters.php
hover on Tour video in Product menu fix
**Checklist**
Close QualityUnit/web-issues#624
> [624] fix: hover on Tour video in Product menu

- base-scripts.php
New gtag AW-966671101 was added.
Check if new gtag working properly.
**Checklist**
Close QualityUnit/web-issues#743
> [743] GTM scripts

- assets/styles/common/elementor-custom.scss
- assets/styles/components/_BlockChannels.scss
- assets/styles/components/_BlockPoints.scss
- assets/styles/components/_BlockPricing.scss
- assets/styles/components/_BlockResearch.scss
- assets/styles/components/_BlockVideo.scss
- assets/styles/components/_Box.scss
- assets/styles/components/_Boxes.scss
- assets/styles/components/_BoxesDotted.scss
- assets/styles/components/_BoxesImage.scss
- assets/styles/components/_BoxesStars.scss
- assets/styles/components/_DemoElement.scss
- assets/styles/components/_Reference.scss
- assets/styles/components/_ShortTrial.scss
- assets/styles/components/_TourPageCTA.scss
- assets/styles/components/_TourPageNumbers.scss
- assets/styles/elements/_ResearchBlock.scss
- assets/styles/layouts/_Research.scss
- assets/styles/layouts/_ResearchPost.scss
- assets/styles/layouts/tests/_RequestDemo.scss
- assets/styles/layouts/tests/_ScheduleDemo.scss
wrong relative urls in elementor-custom.css
**Checklist**
> [586] fix: wrong relative urls

- assets/images/arrow_small_right.svg
- assets/styles/common/_mixins.scss
- assets/styles/components/_Block.scss
- assets/styles/components/_BlockVideo.scss
- assets/styles/components/_BoxesStars.scss
- assets/styles/components/_FeaturesTable-New.scss
- assets/styles/elements/_Typography.scss
Changed learn-more links to 14px globally.
Video box overflow was fixed on full hd resolutions.
Check learn-more link across the LA web.
Check video blocks on desktop.
**Checklist**
Close QualityUnit/web-issues#425
> [425] Social Media Support Page - additional fixes

- assets/scripts/app/custom_lightbox_youtube.js
fixing video iframe insertion on modal videos
**Checklist**
Close QualityUnit/web-issues#756
> [756] fix: fixing video iframe insertion on modal videos

- CHANGELOG.md
- functions.php
- style.css
bump theme version to 1.0.30
**Checklist**
> chore: bump theme version to 1.0.30

- CHANGELOG.md
- functions.php
- style.css
bump theme version to 1.0.31
**Checklist**
> chore: bump theme version to 1.0.31

- assets/styles/common/_global.scss
- assets/styles/components/_BlockSuccess.scss
- assets/styles/components/_FeaturesTable-New.scss
Fixes for tour page redesign
**Checklist**
Close QualityUnit/web-issues#533
> [533] fix: tour page

- CHANGELOG.md
- assets/scripts/custom/IconTabs.js
- assets/scripts/custom/blogLazyLoad.js
- assets/scripts/custom/sidebar_items_slider.js
- assets/scripts/custom/sidebar_toc.js
- functions.php
- lib/shortcodes/good-hands.php
- lib/shortcodes/people.php
- lib/shortcodes/success-stories.php
- style.css
- template-academy-header.php
- template-blog-header.php
- templates/content-archive-ms_research.php
- templates/content-archive.php
Fixes lazyloading of Blog posts and data-lasrc are replaced with data-src for URLsLab plugin compatibility
**Checklist**
> Lazyload fix

- base-scripts.php
- lib/cleaner/assets.php
Revert Google Analytics Back
**Checklist**
Close QualityUnit/web-issues#743
> [743] Revert Google Analytics Back

- assets/styles/components/_BlockPricing.scss
- assets/styles/components/_Box.scss
two small bugfixes to tour page
**Checklist**
Close QualityUnit/web-issues#533
> [533] fix: two small bugfixes to tour page

- lib/cleaner/assets.php
temporary disable remove of block library css
**Checklist**
> fix: temporary disable remove of block library css

- lib/cleaner/wordpress.php
> fix: disable rss

- CHANGELOG.md
- functions.php
- lib/cleaner/assets.php
- style.css
bump theme version to 1.0.33
**Checklist**
> chore: bump theme version to 1.0.33

- assets/styles/components/_BlockSuccess.scss
- assets/styles/components/_Box.scss
- assets/styles/components/_FeaturesTable-New.scss
small fixes to design as requested
**Checklist**
Close QualityUnit/web-issues#533
> [533] fix: small fixes to design as requested

- assets/styles/components/_BlockSolution.scss
Responsive styles of BlockSolution.
Check BlockSolution responsive on Help Desk landing page.
**Checklist**
Close QualityUnit/web-issues#775
> [775] BlockSolution responsive fix

- assets/styles/components/_BlockVideo.scss
Block--video responsive fixes after Optimized DOM Output.
Check Block--video responsive on [Social media](https://www.liveagent.com/social-media-customer-service/) landing page.
**Checklist**
Close QualityUnit/web-issues#778
> [778] Block--video responsive fixes after Optimized DOM Output

- CHANGELOG.md
- functions.php
- lib/cleaner/assets.php
- style.css
bump theme version 1.0.34
**Checklist**
> chore: bump theme version 1.0.34

- CHANGELOG.md
- assets/styles/components/_HeroHeadlineHome.scss
- functions.php
- style.css
Fixed hero images in optimized structure.
Check hero images on landing pages.
**Checklist**
Close QualityUnit/web-issues#
> fix: broken hero images

- CHANGELOG.md
- functions.php
- lib/shortcodes/signup-form-free.php
- lib/shortcodes/signup-form.php
- lib/shortcodes/signup-sidebar.php
- style.css
add google ads tracking
**Checklist**
Close QualityUnit/web-issues#817
> [817] feat: add google ads tracking

- assets/styles/components/_BlockPricing.scss
Mobile view of tags in BlockPricing.
Check BlockPricing and tags on mobile.
**Checklist**
Close QualityUnit/web-issues#818
> [818] tags in BlockPricing block on mobile

- assets/scripts/custom/reviewsGallery.js
- templates/content-single-ms_reviews-top.php
- templates/content-single-ms_reviews.php
Fixing reviews Gallery not working
**Checklist**
> fix: reviews gallery

- .github/workflows/deploy.yml
- .github/workflows/release.yml
chore: add new build script
**Checklist**
> chore: add new build script

- assets/scripts/custom/IconTabs.js
- templates/content-archive-ms_reviews-posts.php
- templates/content-single-ms_reviews.php
icontab chart not loading
**Checklist**
> fix: icontabs reloading on tab switch

- assets/styles/components/_ExtraFaq.scss
- assets/styles/layouts/_Post.scss
- lib/shortcodes/extra-faq.php
- template-academy-header.php
- template-academy.php
- template-blog-header.php
- template-blog.php
- templates/content-single-ms_academy.php
- templates/content-single-ms_checklists.php
- templates/content-single-ms_directory.php
- templates/content-single-ms_features.php
- templates/content-single-ms_glossary.php
- templates/content-single-ms_integrations.php
- templates/content-single-ms_reviews.php
- templates/content-single-ms_templates.php
- templates/content-single.php
(fix: faq and related res. width)
**Checklist**
Close QualityUnit/web-issues#730
> [730] fix: faq and related res. width

- CHANGELOG.md
- functions.php
- style.css
bump theme version to 1.2.0
**Checklist**
> chore: bump theme version to 1.2.0

- CHANGELOG.md
- assets/styles/layouts/_Header.scss
- functions.php
- style.css
Support for both fontello and svg icons in menu
**Checklist**
Close QualityUnit/web-issues#815
> [815] fix: support for both fontello and svg icons in menu

- assets/styles/components/_BlockBadges.scss
Pseudo element as badges image was replaced by previously hidden image.
Check Awards section on homepage and test badges image.
**Checklist**
Close QualityUnit/web-issues#859
> [859] Pseudo element as badges image was removed

- assets/scripts/custom/sidebar_items_slider.js
- assets/scripts/custom/sidebar_toc.js
if the change is correct, pls update also PAP theme
Close https://github.com/QualityUnit/web-issues/issues/878
> Img loading - duplicate loads fix

- CHANGELOG.md
- functions.php
- lib/widgets/qu-checklists/yarn.lock
- lib/widgets/qu-expertnote/yarn.lock
- style.css
bump theme version to 1.3.0
**Checklist**
> chore: bump theme version to 1.3.0

- templates/content-single-ms_reviews-top.php
Showing some resulting HTML only if values are set
**Checklist**
Close QualityUnit/web-issues#884
> [884] fix: conditional values

- lib/shortcodes/signup-sidebar.php
- template-academy-header.php
- template-academy.php
- template-blog-header.php
- template-blog.php
- templates/content-single-ms_about.php
- templates/content-single-ms_academy.php
- templates/content-single-ms_checklists.php
- templates/content-single-ms_directory.php
- templates/content-single-ms_features.php
- templates/content-single-ms_glossary.php
- templates/content-single-ms_integrations.php
- templates/content-single-ms_reviews.php
- templates/content-single-ms_success-stories.php
- templates/content-single-ms_templates.php
- templates/content-single.php
- templates/footer.php
- templates/header.php
skip processing some parts of theme by urlslab plugin
**Checklist**
> fix: skip processing of header, footer and sidebar by urlslab plugin

- lib/shortcodes/clients.php
- lib/shortcodes/language-switcher.php
- template-trial-redesign.php
- templates/header.php
skip lazy load of immediately visible images
**Checklist**
Close QualityUnit/web-issues#866
> [866] feat: skip lazy load of immediately visible images

- lib/shortcodes/signup-sidebar.php
- templates/content-archive-ms_academy.php
- templates/content-archive-ms_checklists.php
- templates/content-archive-ms_features.php
- templates/content-archive-ms_integrations.php
- templates/content-archive-ms_templates.php
- templates/content-archive.php
- templates/footer.php
part of the changes in urlslab pligin processing exceptions
**Checklist**
https://github.com/QualityUnit/web-issues/issues/903
> fix: rename urlslab-skip to urlslab-skip-all

- apps/typing-test/src/app-state/running/index.tsx
- apps/typing-test/src/style.css
- assets/styles/components/_BannerTypingTest.scss
- lib/shortcodes/typing-test.php
Changing build script versioning, few visual tweaks
**Checklist**
Close QualityUnit/web-issues#772
> [772] fix: changing build script versioning, few visual tweaks

- assets/scripts/custom/sidebar_toc.js
FIxed condition to add/remove class on signup sidebar if present
**Checklist**
Close QualityUnit/web-issues#901
> [901] research js errors

- assets/scripts/static/crm_en.js
- assets/scripts/static/crm_se.js
- base-scripts.php
implement SE and JP chat buttons and fixes
**Checklist**
Close QualityUnit/web-issues#461
Close QualityUnit/web-issues#462
> feat: implement SE and JP chat buttons and fixes

- assets/styles/common/_global.scss
Overflow hidden for body.
Check pages scrolling on whole site.
**Checklist**
Close QualityUnit/web-issues#887
> [887] overflow hidden for body

- assets/styles/layouts/_Header.scss
- functions/content-filters.php
change menu item padding for some languages to fix svg icon position
**Checklist**
> fix: svg icon position

- assets/styles/common/_variables.scss
- assets/styles/components/_BlockLearnMore.scss
- assets/styles/components/_ExtraFaq.scss
FAQ one column width.
Check FAQ one column width on landing pages.
**Checklist**
Close QualityUnit/web-issues#908
> [908] FAQ one column width

- assets/styles/components/_HeroHeadlineHome.scss
- template-blog-header.php
Template blog header DOM updated according new elementor optimized DOM Output.
Check [Email management software](http://liveagent.local/email-management-software/) page header and comapre it with hedaders on landing pages.
**Checklist**
Close QualityUnit/web-issues#792
> [792] Template blog header dom updated

- assets/styles/components/_Loader.scss
- assets/styles/layouts/_FullScreen.scss
- assets/styles/pages/TrialRedesign.scss
Css selectors for working wheels fix
**Checklist**
Close QualityUnit/web-issues#880
> [880] fix: css selectors for working wheels

- assets/styles/components/_Loader.scss
Wheels css
**Checklist**
Close QualityUnit/web-issues#880
> [880] fix: wheels

- lib/rest-api/wpml-rest-api.php
- templates/content-archive-ms_reviews-categories.php
- templates/content-archive-ms_reviews.php
- templates/content-archive.php
- templates/content-single-ms_checklists.php
Fixing multiple PHP errors, potencionally related to #915
**Checklist**
Close QualityUnit/web-issues#915
> [915] PHP errors fixing

- templates/content-archive-ms_reviews.php
hiding informal article on level 2
**Checklist**
> fix: hiding informal article on level 2

- assets/scripts/static/login.js
- lib/shortcodes/login.php
Fixing login not working due to script lazy loading changes
**Checklist**
Close QualityUnit/web-issues#916
> [916] fix: non working login

- assets/scripts/app/lazyLoad_apps+widgets.js
- lib/shortcodes/typing-test.php
- lib/shortcodes/web-calc-featured.php
- lib/shortcodes/web-calc.php
lazy loading of widgets/apps resources when in viewport
**Checklist**
Close QualityUnit/web-issues#927
> [927] feat: lazy loading of widgets/apps resources when in viewport

- assets/styles/common/_variables.scss
- assets/styles/components/_Block.scss
- assets/styles/components/_BlockSuccess.scss
- assets/styles/components/_CategoryHeader.scss
- assets/styles/components/_HeroHeadlineHome.scss
- assets/styles/components/_WhatIsHeadline.scss
- assets/styles/layouts/_ErrorPage.scss
- assets/styles/layouts/_Post__header-images.scss
- assets/styles/pages/Checklists.scss
- assets/styles/pages/ChecklistsArchive.scss
- assets/styles/pages/Reviews.scss
- assets/styles/pages/TrialRedesign.scss
- functions/content-filters.php
- lib/widgets/qu-checklists/src/scss/_checklist.scss
replace wrong version param
**Checklist**
> fix: replace wrong version param

- assets/scripts/static/crm.js
- lib/shortcodes/signup-form-free.php
- lib/shortcodes/signup-form.php
- lib/shortcodes/signup-sidebar.php
- set max length for name and mail input
- allow using dash in the domain field
- don't allow to use dot in the name field
**Checklist**
Close QualityUnit/web-issues#897
Close QualityUnit/web-issues#910
Close QualityUnit/web-issues#932
> [897, 910, 932] Trial Signup Improvements and Fixes

- base.php
- templates/head.php
- move styles to correct place
**Checklist**
Close QualityUnit/web-issues#889
> [889] fix: move styles to correct place

- functions/content-filters.php
- add trailing slash at the end of a link
**Checklist**
Close QualityUnit/web-issues#940
> [940] feat: add trailing slash at the end of a link

- assets/scripts/custom/sidebar_toc.js
- assets/styles/components/BlockPoints.scss
- assets/styles/components/BlockVideo.scss
- assets/styles/components/_Block.scss
- assets/styles/components/_Reference.scss
- assets/styles/layouts/_Post.scss
- assets/styles/shortcodes/BlockDiscover.scss
- assets/styles/shortcodes/ShortTrial.scss
fixing sidebar scroll, few css bugs
**Checklist**
Close QualityUnit/web-issues#937
> [937] fix: fixing sidebar scroll, few css bugs

- gulpfile.js
- package.json
- yarn.lock
Fix icons builder for new @xmldom/xmldom parser changes
**Checklist**
> Fix icons builder

- gulpfile.js
> fix: icon builder

- assets/styles/components/BlockCoupon.scss
- assets/styles/shortcodes/Countdown.scss
Allowing custom text colors via elementor and banner max height via --maxHeight CSS variable in BlockCoupon
**Checklist**
> [951] Countdown banner

- assets/styles/components/BlockCoupon.scss
adding original gradient to the countdown banner
**Checklist**
Close QualityUnit/web-issues#951
> [951] fix: adding original gradient to the countdown banner

- assets/styles/components/BlockCoupon.scss
- functions/components-imports.php
Fixing bad condition to import css on class occurence
**Checklist**
> fix: component import function

- functions/get-posts.php
> fix: changing loop to get only IDs of posts

- assets/styles/pages/Directory.scss
- functions/get-posts.php
- lib/metaboxes/reviews.php
- templates/content-single-ms_reviews-contacts.php
attempt to fix php performance
**Checklist**
> fix: attempt to fix php performance

- contactus-box.php
phone number change
**Checklist**
Close QualityUnit/web-issues#935
> [935] fix: phone number change

- assets/styles/layouts/_BlogPost.scss
- lib/shortcodes/author.php
Fixed coauthor blog photo sizing
**Checklist**
Close QualityUnit/web-issues#974
> [974] fix: coauthor image size and lazyload

- assets/styles/elements/_Typography.scss
- templates/content-archive-ms_reviews-categories.php
header tags and texts
**Checklist**
Close QualityUnit/web-issues#972
> [972] fix: header tags and texts

- functions.php
- functions/sitemap-filters.php
- templates/footer.php
Fix for Yoast SEO sitemap Reviews 404 links
**Checklist**
Close QualityUnit/web-issues#968
Close QualityUnit/web-issues#966
> [968] fix: 404 in sitemap.xml

- templates/content-archive-ms_features.php
read more button with title
**Checklist**
Close QualityUnit/web-issues#978
> [978] fix: read more button with title

- contactus-box.php
Conditional phone number in contact us options
**Checklist**
Close QualityUnit/web-issues#935
> [935] fix: conditional phone number in contact us options

- assets/styles/layouts/_BlogPost.scss
- composer.lock
- contactus-box.php
- lib/research-block-filters.php
added urlslab-skip-all class, fixed guest author image
**Checklist**
Close QualityUnit/web-issues#957
Close QualityUnit/web-issues#974
> [957] fix: added urlslab-skip-all class, fixed guest author image

- assets/styles/elements/_Button.scss
- assets/styles/elements/_Typography.scss
change paths for 404 images
**Checklist**
> fix: change paths for 404 images

- assets/scripts/app/custom_lightbox_youtube.js
- assets/scripts/app/toggleVisibility.js
- functions/import-functions.php
- lib/extras.php
Visibility switcher fixed to handle cases where one item shoud be alway active
**Checklist**
Close QualityUnit/web-issues#987
> [987] fix: visibility switcher

- templates/content-archive.php
archive php bug conditional check
**Checklist**
Close QualityUnit/web-issues#988
> [988] fix: archive php bug

- functions/sidebar-toc.php
- lib/pagesources.php
- templates/content-archive-ms_reviews.php
added sidebars to reviews category what is post, blog header fix
**Checklist**
Close QualityUnit/web-issues#989
Close QualityUnit/web-issues#990
> [989] fix: added sidebars to reviews category what is post, blog header fix

- assets/styles/layouts/_Research.scss
- assets/styles/pages/Checklists.scss
- templates/content-single-ms_checklists.php
- templates/content-single-ms_research.php
multiple improvements of mobile lcp
**Checklist**
> [995] fix: multiple improvements of mobile lcp

- functions/get-posts.php
fix: load articles only when on ms reviews
**Checklist**
> fix: load articles only when on ms reviews

- assets/styles/components/Signup.scss
- lib/shortcodes/signup-form.php
- template-trial-redesign.php
Changed trial duration tags on trial page and signup forms.
Check trial duration tags across all pages.
**Checklist**
Close QualityUnit/la-marketing#2455
> [2455] Changed trial duration tags

- assets/styles/Elementor.scss
Add styles for Affiliate program signup page.
Check styles for Affiliate program signup page.
**Checklist**
Close QualityUnit/web-issues#1003
> [1003] Styles for Affiliate program signup page

- assets/images/arrow_small_right.svg
- assets/styles/common/_mixins.scss
- assets/styles/components/BlockVideo.scss
- assets/styles/components/FeaturesTable-New.scss
- assets/styles/components/_Block.scss
- assets/styles/components/_BoxesStars.scss
- assets/styles/elements/_Typography.scss
- functions/content-filters.php
Updates for learn-more link:
- new icon for from icons.svg
- arrow animation on hover
Check learn-more links on web
**Checklist**
Close QualityUnit/web-issues#985
> [985] Learn-more arrow updates

- lib/widgets/qu-commonproblems/includes/cp-item.php
removing schema from common problems widget
**Checklist**
Close QualityUnit/web-issues#1023
> [1023] fix: removing schema from common problems widget

- lib/pagesources.php
change pricing resources reference
**Checklist**
Close QualityUnit/web-issues#2418
> [2418] fix: change pricing resources reference

- assets/styles/layouts/_ComparePlansNew.scss
fix of margin in new pricing table
**Checklist**
> [2418] fix: compare tables margin

- base-scripts.php
add offline button instead of nothing
**Checklist**
Close QualityUnit/web-issues#1009
> feat: add offline button instead of nothing

- functions/rest-api.php
- lib/post-types/pricing-tables.php
hiding post type Pricing Tables from public
> [2418] fix: hiding post type from public

- assets/styles/components/Signup.scss
Overflow hidden for signup form.
Check if horizontal scrollbar is still appears on landing pages.
**Checklist**
Close QualityUnit/web-issues#1035
> [1035] Remove Horizontal Scrollbar

- templates/content-archive-ms_reviews-posts.php
remove aggregateratingback from review main item
**Checklist**
> fix: remove aggregateratingback from review main item

- assets/styles/components/_ContactUs.scss
- assets/styles/elements/_FakeChatButton.scss
- contactus-box.php
- templates/content-single-ms_reviews-top.php
contact form ids, reviews category_slug missing
**Checklist**
Close QualityUnit/web-issues#1022
Close QualityUnit/web-issues#1027
> [1022] fix: contact form ids, reviews category_slug missing

- assets/styles/components/_Block.scss
Small spacing between blocks.
Check spacing between title section and next section.
**Checklist**
Close QualityUnit/web-issues#997
> [997] small spacing between blocks

- assets/styles/Elementor.scss
Added styles for typing test banner to elementor.
Check typing test banner on [Typing Test page](https://admin.liveagent.com/typing-test/).
**Checklist**
Close QualityUnit/web-issues#1026
> [1026]: typing test banner

- assets/styles/elements/_ReviewsRating.scss
- templates/content-single-ms_reviews-top.php
small author tweak in Reviews editor rating
**Checklist**
Close QualityUnit/web-issues#1052
> [1052] fix: small author tweak

- assets/styles/pages/Reviews.scss
- templates/content-archive-ms_reviews.php
how we review article width
**Checklist**
Close QualityUnit/web-issues#1058
> [1058] fix: how we review article width

- assets/styles/components/BlockVideo.scss
- assets/styles/layouts/_ComparePlansNew.scss
- assets/styles/layouts/_PricingEnterprise.scss
- assets/styles/layouts/_PricingPrograms.scss
- assets/styles/layouts/_PricingTop.scss
small changes to pricing
**Checklist**
Close QualityUnit/la-marketing#2418
> [2418] fix: small changes to pricing

- templates/head.php
- remove not effective preloads
**Checklist**
> [995] optimize web vitals

- base-scripts.php
add web vitals tracking
**Checklist**
> [995] feat: add web vitals tracking

- lib/assets.php
- lib/cleaner/assets.php
- reorder css loading
**Checklist**
> [995] Optimize Web Vitals v3

- assets/scripts/custom/slider.js
gutenberg slider fix not loading
**Checklist**
Close QualityUnit/web-issues#1069
> [1069] fix: gutenberg slider

- assets/styles/components/_DemoBar.scss
- assets/styles/layouts/_Post.scss
- templates/footer.php
small fixes
**Checklist**
Close QualityUnit/web-issues#1063
Close QualityUnit/web-issues#1076
Close QualityUnit/web-issues#1077
> [1063] fix: small fixes

- assets/styles/components/_DemoBar.scss
demobar size on smaller screens
Close QualityUnit/web-issues#1063
> [1063] fix: demobar size on smaller screens

- lib/cleaner/assets.php
[Describe what was changed in the Pull Request](fix: replacing buffer special char to remove unwanted css and scripts)
**Checklist**
> fix: replacing buffer special char to remove unwanted css and scripts

- assets/scripts/static/crm.js
- base-scripts.php
- add twitter tracking and dreamdata trial tracking
**Checklist**
Close QualityUnit/web-issues#1082
Close QualityUnit/web-issues#1083
> [1082, 1083] feat: add twitter tracking and dreamdata trial tracking

- contactus-box.php
-  external contact us links are nofollow now
**Checklist**
Close QualityUnit/web-issues#1078
> [1078] fix: external contact us links nofollow

- base-scripts.php
- lib/shortcodes/login.php
- lib/shortcodes/signup-form-free.php
- lib/shortcodes/signup-form-simple.php
- lib/shortcodes/signup-form.php
- lib/shortcodes/signup-sidebar.php
quick fix of cookie bar
**Checklist**
> chore: quick fix of cookie bar

- assets/styles/common/_mixins.scss
- assets/styles/components/_Boxes.scss
- assets/styles/shortcodes/SliderSuccessStories.scss
- lib/shortcodes/slider-success-stories.php
- Homepage feedback changes according [figma design comments](https://www.figma.com/file/wHsfUE1z4g0GF0NjrRCcLh/LA-WEB-RfD---Homepage?node-id=470%3A262&t=zi5A9dXEGqgZBCkn-0).
- "learn-more" styles and mixins
Check homepage changes
**Checklist**
Close QualityUnit/web-issues#1065
> [1065] Homepage feedback changes

- assets/scripts/static/crm.js
- assets/styles/components/_SignupFormSimple.scss
- assets/styles/elements/_Tooltip.scss
- lib/shortcodes/signup-form-simple.php
Signup ab testing bugfixes
**Checklist**
Close QualityUnit/web-issues#1059
> [1059] Signup ab testing bugfixes

- apps/web-calc-featured/src/assets/style/common/_variables.scss
- apps/web-calc/src/assets/style/common/_variables.scss
- assets/styles/common/_variables.scss
- assets/styles/common/elementor-custom.scss
- assets/styles/components/IconTabs.scss
- assets/styles/components/SidebarTOC.scss
- assets/styles/components/_Block.scss
- assets/styles/components/_Boxes.scss
- assets/styles/components/_BoxesStars.scss
- assets/styles/components/_CategoryItem.scss
- assets/styles/components/_ExtraFaq.scss
- assets/styles/components/_HeroHeadlineHome.scss
- assets/styles/elements/_PostTypography.scss
- assets/styles/elements/_Typography.scss
- assets/styles/layouts/Footer.scss
- assets/styles/layouts/Header.scss
- assets/styles/layouts/_Research.scss
- assets/styles/layouts/_ResearchPost.scss
- assets/styles/pages/Archive.scss
- assets/styles/pages/SuccessStoriesArticle.scss
- assets/styles/shortcodes/BlockDiscover.scss
- lib/shortcodes/discover-alternatives.php
- lib/shortcodes/discover.php
- improvements based on pagespeed
**Checklist**
> feat: improvements based on pagespeed

- apps/web-calc-featured/src/assets/style/common/_variables.scss
- apps/web-calc/src/assets/style/common/_variables.scss
- assets/styles/common/_variables.scss
- assets/styles/common/elementor-custom.scss
- assets/styles/components/SignupSidebar.scss
- assets/styles/components/_BlogHeader.scss
- assets/styles/components/_CategoryItem.scss
- assets/styles/components/_ExtraFaq.scss
- assets/styles/components/_HeaderLanguageSwitcher.scss
- assets/styles/elements/_PostTypography.scss
- assets/styles/elements/_Typography.scss
- assets/styles/layouts/_Blog.scss
- assets/styles/layouts/_BlogPost.scss
- assets/styles/layouts/_Pricing.scss
- assets/styles/layouts/_ReviewsCategories.scss
- assets/styles/layouts/_ReviewsPosts.scss
- assets/styles/pages/About.scss
- assets/styles/pages/Archive.scss
- assets/styles/pages/Checklists.scss
- assets/styles/pages/SuccessStoriesArticle.scss
- templates/footer.php
- templates/header.php
- multiple improvements and fixes
**Checklist**
Close QualityUnit/web-issues#1098
Close QualityUnit/la-marketing#2705
> [1098, 2705] feat: multiple improvements and fixes

- contactus-box.php
- lib/shortcodes/block-quote.php
- lib/shortcodes/blog-cta.php
- lib/shortcodes/discover.php
- templates/content-archive-ms_reviews-categories.php
- templates/content-archive-ms_reviews-posts.php
- templates/content-archive-ms_success-stories.php
- templates/content-single-ms_reviews-top.php
- add slash at the end of links
**Checklist**
Close QualityUnit/web-issues#1078
> [1078] fix: add slash at the end of links

- assets/styles/layouts/_PricingTop.scss
fixing tabs on mobile
**Checklist**
Close QualityUnit/web-issues#1093
> [1093] fix: fixing tabs on mobile

- assets/styles/elements/_Button.scss
- assets/styles/layouts/_PricingPrograms.scss
- base.php
- lib/extras.php
- lib/pagesources.php
Pricing enterprise css/js paths for production
**Checklist**
> Pricing enterprise for production

- lib/shortcodes/block-pricing.php
- change texts in small pricing element
**NOTE: DO NOT MERGE AND DEPLOY BEFORE THE NEW PRICING IS RELEASED!**
**Checklist**
Close QualityUnit/web-issues#1045
> [1045] feat: change texts in small pricing element

- assets/scripts/custom/pricingNew.js
- assets/styles/common/_reset.scss
- assets/styles/common/elementor-custom.scss
- assets/styles/layouts/_ComparePlansNew.scss
- assets/styles/layouts/_PricingEnterprise.scss
- assets/styles/layouts/_PricingPrograms.scss
- assets/styles/layouts/_PricingTop.scss
Multiple bugfixes on mobile Pricing new/enterprise
**Checklist**
> fix: multiple mobile bugfixes

- assets/scripts/static/crm.js
- show more descriptive error messages
**Checklist**
Close QualityUnit/web-issues#1105
> [1105] feat: show more descriptive error messages

- assets/styles/components/_Boxes.scss
- assets/styles/layouts/_HelpDesk.scss
New Boxes--home style with wide image.
HelpDesk section margins.
Check redesign of [Customer service software](https://admin.liveagent.com/customer-service-software-2/) page.
**Checklist**
Close QualityUnit/web-issues#838
> [838] Blocks changes for custom service software page

- assets/styles/components/FeaturesTable-New.scss
- assets/styles/components/_Box.scss
New box link classes.
Style changes for ".FeaturesTableNew" section.
**Checklist**
Close QualityUnit/web-issues#998
> [998] Tour page redesign fixes

- templates/content-archive-ms_reviews.php
Fixed empty review category description in html output.
Check review category heading html output.
**Checklist**
Close QualityUnit/web-issues#1110
> [1110] Empty category description

- assets/styles/components/_ReviewsGallery.scss
- assets/styles/pages/Reviews.scss
- templates/content-single-ms_reviews-top.php
- templates/content-single-ms_reviews.php
Changed Headings hierarchy according issue on review pages.
Check headings hierarchy on review pages.
**Checklist**
Close QualityUnit/web-issues#1109
> [1109] Headings hierarchy on review pages

- template-trial-redesign.php
- template-trial.php
change trial signup texts
**Checklist**
Close QualityUnit/web-issues#1126
> [1126] feat: change trial signup texts

- assets/styles/layouts/_PricingEnterprise.scss
- assets/styles/layouts/_PricingPrograms.scss
Polishing up pricing and pricing/enterprise responsivity on tablets
**Checklist**
Close QualityUnit/web-issues#1130
> [1130] fix: pricing responsivity

- lib/metaboxes/features.php
- lib/metaboxes/integrations.php
- lib/metaboxes/reviews.php
- lib/shortcodes/block-pricing.php
- lib/shortcodes/short-pricing.php
- templates/content-archive-ms_features.php
- templates/content-single-ms_features.php
- templates/content-single-ms_integrations.php
- templates/content-single-ms_reviews-top.php
- change names of plans
**Checklist**
Close QualityUnit/web-issues#1132
> [1132] feat: change names of plans

- assets/styles/components/_Box.scss
- assets/styles/shortcodes/WordCloud.scss
- remove underline from links
**Checklist**
Close QualityUnit/web-issues#1127
> [1127] fix: remove underline from links

- assets/styles/pages/TrialRedesign.scss
- fix trial logo link
**Checklist**
> fix: trial logo link

- assets/styles/components/_SimilarSources.scss
- fix related resources links
**Checklist**
> fix: related resources links

- assets/styles/components/IconTabs.scss
- assets/styles/components/SidebarTOC.scss
- assets/styles/components/SignupSidebar.scss
- assets/styles/elements/_PostTypography.scss
- gulpfile.js
- templates/content-single-ms_directory.php
- templates/content-single-ms_reviews-contacts.php
-  multiple small fixes
**Checklist**
> fix: multiple small fixes

- assets/styles/shortcodes/BlockPricing.scss
Fixed padding in "BlockPricing" section with "Block" class.
Check "BlockPricing" section with "Block" class.
**Checklist**
Close QualityUnit/web-issues#838
> [838] Spacing in pricing block

- assets/styles/components/FeaturesTable-New.scss
- assets/styles/components/_Block.scss
- assets/styles/components/_Boxes.scss
- assets/styles/components/_HeroHeadlineHome.scss
Implemented [figma](https://www.figma.com/file/38sLUgN8UB6MfSJd1a4S9G/LA-WEB-RfD---Tour-page?node-id=513%3A12129&t=CZRAl9Zmfw10PQsm-0) comments.
- Blocks spacing.
- Home blocks style changes.
- Hero section text size.
- Feature table style changes.
Check Tour page changes according [figma](https://www.figma.com/file/38sLUgN8UB6MfSJd1a4S9G/LA-WEB-RfD---Tour-page?node-id=513%3A12129&t=CZRAl9Zmfw10PQsm-0) design.
**Checklist**
Close QualityUnit/web-issues#998
> [998] Implemented figma comments

- assets/styles/layouts/_ComparePlansNew.scss
Changed z index of pricing plans sticky header.
Check bubbles in pricing.
**Checklist**
Close QualityUnit/web-issues#1148
> [1148] Z-index pricing plans sticky header

- assets/styles/shortcodes/Clients.scss
Clients logos horizontal alignment in good hands shortcode.
Check client logos horizontal alignment at the bottom of page.
**Checklist**
Close QualityUnit/web-issues#998
> [998] Clients logos horizontal alignment in good hands shortcode

- assets/scripts/static/crm.js
- send ga4 id to crm
**Checklist**
Close QualityUnit/la-marketing#2486
> [2486] feat: send ga4 id to crm

- assets/scripts/app/tooltips.js
- assets/styles/elements/_Tooltip.scss
Tooltip fixes:
- hover on bubble
- z-index on pricing page
Check tooltips across the web.
**Checklist**
Close QualityUnit/web-issues#1148
> [1148] Tooltip fixes

- .idea/jsLibraryMappings.xml
- assets/styles/components/_Block.scss
- assets/styles/components/_ContactUs.scss
- assets/styles/components/_ExtraFaq.scss
- assets/styles/layouts/_Post.scss
- assets/styles/layouts/tests/RequestDemo.scss
- assets/styles/pages/CategoryImages.scss
- functions/content-filters.php
- lib/metaboxes/features.php
- templates/content-archive-ms_features.php
Multiple Fixes and Improvements
**Checklist**
Close QualityUnit/web-issues#1292
Close QualityUnit/web-issues#1228
Close QualityUnit/web-issues#1154
Close QualityUnit/web-issues#1129
Close QualityUnit/web-issues#1114
Close QualityUnit/web-issues#1171
Close QualityUnit/web-issues#1212
Close QualityUnit/web-issues#1231
> Multiple Fixes and Improvements

- assets/styles/components/_SimilarSources.scss
- elementor.php
- template-academy-header.php
- template-academy.php
- template-blog-header.php
- template-blog.php
- templates/content-page.php
- templates/content-single-ms_academy.php
- templates/content-single-ms_checklists.php
- templates/content-single-ms_features.php
- templates/content-single-ms_glossary.php
- templates/content-single-ms_integrations.php
- templates/content-single-ms_reviews.php
- templates/content-single-ms_templates.php
- templates/content-single.php
New Related Articles
**Checklist**
Close QualityUnit/web-issues#1181
> [1181] New Related Articles

- assets/styles/layouts/_ReviewsPosts.scss
set max-height for review excerpt
**Checklist**
Close QualityUnit/web-issues#1358
> [1358] fix: set max-height for review excerpt

- templates/content-single-ms_glossary.php
implement first element with ai generation
**Checklist**
Close QualityUnit/web-issues#1415
> [1415] feat: implement first element with ai generation

- base-scripts.php
GA4 domain linker fixed
**Checklist**
Close QualityUnit/web-issues#1428
> [1428] fix: GA4 domain linker

- composer.lock
New webinars icon
Close QualityUnit/web-issues#1526
> [1526] fix: updating webinars icon from repo

- composer.lock
> [1526] fix: adding videos icon

- assets/scripts/app/videoTranscript.js
- assets/styles/app.scss
- assets/styles/shortcodes/VideoTranscript.scss
- templates/content-single-ms_videos.php
Youtube video transcript for urlslab plugin
Close QualityUnit/web-issues#1489
> [1489] youtube captions

- templates/content-single-ms_checklists.php
- templates/content-single-ms_directory.php
- templates/content-single-ms_features.php
- templates/content-single-ms_glossary.php
- templates/content-single-ms_integrations.php
- templates/content-single-ms_research.php
- templates/content-single-ms_reviews.php
- templates/content-single-ms_templates.php
- templates/content-single-ms_videos.php
- templates/content-single.php
Compact header text generated by function for single posts.
Check compact header description in compact headers.
**Checklist**
Close QualityUnit/web-issues#1572
> [1572] compact header text generated by function

- templates/content-archive-ms_videos.php
- templates/content-single-ms_checklists.php
- templates/content-single-ms_directory.php
- templates/content-single-ms_features.php
- templates/content-single-ms_glossary.php
- templates/content-single-ms_integrations.php
- templates/content-single-ms_research.php
- templates/content-single-ms_reviews.php
- templates/content-single-ms_templates.php
- templates/content-single-ms_videos.php
- templates/content-single.php
Compact header summary generated by function in videos.
Check compact header summary generated by function in videos.
**Checklist**
Close QualityUnit/web-issues#1572
> [1572] Description in compact header

- base-scripts.php
- lib/shortcodes/signup-form-simple.php
- lib/shortcodes/signup-form.php
- lib/shortcodes/signup-sidebar.php
reintegrate gtm with new tracking
**Checklist**
Close QualityUnit/web-issues#1558
> [1558] feat: revert gtm

- templates/content-single-ms_directory.php
Added missing slashes in compact header tags.
Check missing slashes in compact header tags
**Checklist**
Close QualityUnit/web-issues#1609
> [1609] Added missing slashes in compact header tags

- assets/styles/layouts/_Custom.scss
- lib/assets.php
- lib/custom-blocks/compact-header.php
- templates/content-single-ms_directory.php
- some improvements for cls
**Checklist**
> feat: some improvements for cls

- template-blog-header.php
Compact header for pages with block header template.
Check compact header on pages with block header template.
**Checklist**
Close QualityUnit/web-issues#1211
> [1211] Compact Header in Blog Header Template

- assets/styles/components/BlockVideo.scss
- assets/styles/shortcodes/VideoTranscript.scss
- templates/content-single-ms_videos.php
video glitches
Close QualityUnit/web-issues#1608
> [1608] fix: video glitches

- assets/styles/components/_Reviews.scss
Home integrations mobile fix.
Check home integrations section on mobile.  (check also elementor changes in issue comments)
**Checklist**
Close QualityUnit/web-issues#1663
> [1663] Home integrations mobile fix

- assets/styles/components/compactHeader.scss
- assets/styles/shortcodes/BlockDiscover.scss
Small fixes in compact header.
Check pages with compact header and discover block.
**Checklist**
Close QualityUnit/web-issues#1034
> [1034] Compact header small fixes

- templates/footer.php
add urlslab skip all to building app container
**Checklist**
> fix: add urlslab skip all to building app container

- assets/styles/layouts/_PricingPrograms.scss
Added free account section and fix some bugs on pricelist page
**Checklist**
Close QualityUnit/web-issues#1706
> [1706] LA pricing list changes

- templates/footer.php
Added class to element loader for ignoring urslab addon
**Checklist**
Close QualityUnit/web-issues#1089
> [1089] fixed lazy load for videos

- assets/scripts/static/crm.js
- assets/styles/layouts/_PricingPrograms.scss
- lib/shortcodes/introduction-videos.php
changed data attributes and add styles for price on pricing list
**Checklist**
Close QualityUnit/web-issues#1089
> [1089] change data src to data src trial and style for pricinglist

- assets/styles/components/_CategoryItem.scss
- assets/styles/pages/Category.scss
fixed margins between items and replaced color mixins
**Checklist**
Close QualityUnit/web-issues#1712
> [1712] fix margins and replace color mixins

- lib/shortcodes/login.php
- lib/shortcodes/signup-form-free.php
- lib/shortcodes/signup-form-simple.php
- lib/shortcodes/signup-form.php
[Describe what was changed in the Pull Request](fix: loading lang files for crm and login before actual script)
Close QualityUnit/web-issues#1772
> [1772] fix: loading lang files for crm and login before actual script

- assets/styles/components/Signup.scss
added left margin to info icon in trial form
**Checklist**
Close QualityUnit/web-issues#1771
> [1771] added margin to info icon in trial form

- assets/scripts/app/signup_login_js_loader.js
- assets/scripts/static/login.js
form not setting crm type, global for localStorage removed
Close QualityUnit/web-issues#1782
> [1782] fix: form not setting crm type

- assets/scripts/static/crm-redeemcode.js
- assets/scripts/static/crm.js
- assets/styles/components/_Loader.scss
- lib/shortcodes/introduction-videos.php
- lib/shortcodes/signup-form-free.php
- lib/shortcodes/signup-form-redeemcode.php
- lib/shortcodes/signup-form-simple.php
- lib/shortcodes/signup-form.php
- lib/shortcodes/signup-sidebar.php
- templates/footer.php
login button not working, fixed by rewrite part of crm to pure javascript, multiple other fixes
Close QualityUnit/web-issues#1784
> [1784] fix: login button not working

- lib/shortcodes/signup-form-free.php
- lib/shortcodes/signup-form-redeemcode.php
- lib/shortcodes/signup-form-simple.php
- lib/shortcodes/signup-form.php
- lib/shortcodes/signup-sidebar.php
functions bugs
Close QualityUnit/web-issues#1784
> [1784] fix: functions bugs

- assets/scripts/static/crm.js
- lib/shortcodes/introduction-videos.php
Close QualityUnit/web-issues#1784
> [1784] fix: continue watching button

- assets/scripts/custom/pricingNew.js
fixed switch on the pricing page.
**Checklist**
Close QualityUnit/web-issues#1770
> [1770]  LA Pricing All features switch is not working 

- assets/styles/components/_CategoryItem.scss
- assets/styles/components/_SignupFormSimple.scss
- assets/styles/elements/_Typography.scss
- assets/styles/layouts/_PricingPrograms.scss
- package.json
- yarn.lock
dart sass deprecation errors, old flex vals
Close QualityUnit/web-issues#1787
> [1787] fix: dart sass deprecation, old flex vals

- assets/styles/components/_AiWhisperAssistent.scss
add new padding and max height for img in ai whisper element
**Checklist**
Close QualityUnit/web-issues#1630
> [1630] AI Features Promotions

- templates/content-single-ms_checklists.php
added '#' to category link in breadcrumb
**Checklist**
Close QualityUnit/web-issues#1781
> [1781] fix bugged link in breadcrumb

- assets/styles/components/AnnouncementBar.scss
modified top values ​​so that the sub menu works
**Checklist**
Close QualityUnit/web-issues#1863
> [1863] If is AI bar visible sub menu is broken

- assets/scripts/static/crm-free_ae.js
- assets/scripts/static/crm-free_bg.js
- assets/scripts/static/crm-free_br.js
- assets/scripts/static/crm-free_cn.js
- assets/scripts/static/crm-free_cr.js
- assets/scripts/static/crm-free_cz.js
- assets/scripts/static/crm-free_de.js
- assets/scripts/static/crm-free_dk.js
- assets/scripts/static/crm-free_ee.js
- assets/scripts/static/crm-free_es.js
- assets/scripts/static/crm-free_fi.js
- assets/scripts/static/crm-free_fr.js
- assets/scripts/static/crm-free_gr.js
- assets/scripts/static/crm-free_hu.js
- assets/scripts/static/crm-free_it.js
- assets/scripts/static/crm-free_jp.js
- assets/scripts/static/crm-free_lt.js
- assets/scripts/static/crm-free_lv.js
- assets/scripts/static/crm-free_nl.js
- assets/scripts/static/crm-free_no.js
- assets/scripts/static/crm-free_ph.js
- assets/scripts/static/crm-free_pl.js
- assets/scripts/static/crm-free_ro.js
- assets/scripts/static/crm-free_ru.js
- assets/scripts/static/crm-free_se.js
- assets/scripts/static/crm-free_si.js
- assets/scripts/static/crm-free_sk.js
- assets/scripts/static/crm-free_vn.js
free crm js not working other langs – bad session storage variable name
Close QualityUnit/web-issues#1815
> [1815] fix: free crm js not working other langs

- templates/content-single-ms_integrations.php
[Describe what was changed in the Pull Request](fix: removing faq title from integrations)
> fix: removing faq title from integrations

- assets/styles/common/_animations.scss
- assets/styles/components/_HorizontalTabs.scss
style management because the elementor tab structure has changed and some code cleanup
**Checklist**
Close QualityUnit/web-issues#1858
> [1858] Broken element on our product pages

- assets/styles/components/_CategoryItem.scss
- templates/content-archive-ms_videos.php
Close QualityUnit/web-issues#1888
> [1888] fix: redesign video section

- assets/styles/components/_CategoryItem.scss
Close QualityUnit/web-issues#1888
> [1888] fix: long urls breaking videos design

- assets/styles/layouts/_PricingPrograms.scss
Added styles to fix visual bugs
**Checklist**
Close QualityUnit/web-issues#1706
> [1706] LA pricing bugs

- assets/styles/components/_HeroBanner.scss
- assets/styles/shortcodes/Clients.scss
**Checklist**
Close QualityUnit/web-issues#1209
> [1209] redesign of feader elementor block

- functions/metaboxes.php
- lib/metaboxes/signup-sidebar.php
- lib/shortcodes/signup-sidebar.php
added editing of signup form in sidebar
Close QualityUnit/web-issues#1967
> [1967] feat: editing of signup form in sidebar

- templates/content-single-ms_integrations.php
fixed texts on single page of integrations post type
**Checklist**
Close QualityUnit/web-issues#2011
> [2011]  Lorem ipsum on LA integrations

- lib/shortcodes/signup-sidebar.php
renaming function to get meta in shortcode to avoid redefining
Close QualityUnit/web-issues#2027
> [2027] fix: meta function rename

- contactus-box.php
- functions.php
- functions/remove-base-classes.php
added filter to remove class that adds wordpress to the menu of li elements and addition of javascript help information to whatsapp chat in the contact us widget
**Checklist**
Close QualityUnit/web-issues#1962
> [1962] Optimize the Footer and Contact Widget for better caching 

- base-scripts.php
Added conditions so that there are no errors in the console
**Checklist**
Close QualityUnit/web-issues#2050
> [2050] The announcement bar makes an error in the console

- apps/web-calc-featured/src/components/layouts/finalResults.jsx
- apps/web-calc-featured/src/data/i18n/en.json
Added additional text for knowledgebase webcalc title
Close QualityUnit/web-issues#1652
> [1652] feat: additional text for knowledgebase webcalc title

- assets/styles/components/_HeroBanner.scss
I unified the styles for the text editor
**Checklist**
Close QualityUnit/web-issues#2056
> [2056] LA product pages subtitle

- assets/scripts/custom/blogLazyLoad.js
- base-scripts.php
- templates/content-archive-ms_reviews.php
- templates/content-archive.php
blog lazyloading binded to loader instead of footer
Close QualityUnit/web-issues#2085
> [2085] fix: blog lazyloading binded to loader instead of footer

- templates/content-single-ms_videos.php
Text correction
**Checklist**
Close QualityUnit/web-issues#2044
> [2044] Typo in LA videos 

- base-scripts.php
replace analytics v4 to gtm where is analytics stored
reason: offline conversions
**Checklist**
> feat: new gtm

- templates/content-single-ms_features.php
- templates/content-single-ms_reviews.php
- templates/content-single.php
added faq shortcode to more templates
Close QualityUnit/web-issues#2118
> [2118] feat: added faq shortcode to more templates

- assets/styles/layouts/_BlogPost.scss
- templates/content-single.php
Removed old related section on blog posts
**Checklist**
Close QualityUnit/web-issues#2121
> [2121] Remove double related articles

- functions/import-functions.php
Close https://github.com/QualityUnit/web-issues/issues/2186
> fix: handling if categories as array

- apps/web-calc-featured/src/assets/style/common/_typography.scss
- apps/web-calc-featured/src/components/elements/agentsSlider.jsx
- apps/web-calc/src/assets/style/common/_typography.scss
- apps/web-calc/src/components/elements/agentsSlider.jsx
changed element h4 to p in react app web calc
**Checklist**
Close QualityUnit/web-issues#1520
> [1520] Ticketing Software Changes

- templates/content-single-ms_academy.php
I changed the code for generating the description in academy single
**Checklist**
Close QualityUnit/web-issues#2214
> [2214] Incomplete AI-generated descriptions in LiveAgent's articles

- templates/content-single-ms_templates.php
added support for urlslab faq on postype templates single
**Checklist**
Close QualityUnit/web-issues#2207
> [2207] LA Email templates missing FAQ

- templates/content-single-ms_glossary.php
html tags in expert note
Close QualityUnit/web-issues#2119
> [2119] fix: html tags in expert note

- assets/styles/elements/_BulletLists.scss
fixed styles for bullet lists
**Checklist**
Close QualityUnit/web-issues#2213
> [2213] Broken Pros and Cons - LA web

- base-scripts.php
added JS to control scrolling in content.
**Checklist**
Close QualityUnit/web-issues#2095
> [2095] "Table of contents" block has broken formatting

- assets/styles/elements/_Typography.scss
i changed style for text color
**Checklist**
Close QualityUnit/web-issues#2368
> [2368] mprovement request for LiveAgent's templates

- assets/styles/shortcodes/_UrlslabFaq.scss
I added styles for the FAQ section 
**Checklist**
Close QualityUnit/web-issues#2248
> [2248] LA, PAP: please change FAQ from double collumn to one

- assets/styles/pages/TrialRedesign.scss
I Added shadow to trial page
**Checklist**
Close QualityUnit/web-issues#1180
> [1180] Missing Shadow on Trial Page

- lib/widgets/qu-checklists/checklists.php
- lib/widgets/qu-checklists/src/components/CheckListItem.js
- lib/widgets/qu-checklists/src/components/Editor.js
- lib/widgets/qu-checklists/src/edit.js
- lib/widgets/qu-checklists/src/edit_checklistitem.js
- lib/widgets/qu-checklists/src/frontend.js
- lib/widgets/qu-checklists/yarn.lock
- lib/widgets/qu-howtos/src/components/Editor.js
- lib/widgets/qu-howtos/src/components/HowToItem.js
- lib/widgets/qu-howtos/src/edit.js
- lib/widgets/qu-howtos/src/edit_howtoitem.js
checklist and how to widgets not working after wp update
Close QualityUnit/web-issues#2394
Close QualityUnit/web-issues#2413
> [2413] fix: checklist and how to widgets not working after wp update

- templates/content-archive-ms_reviews.php
what is posts translation in reviews
Close QualityUnit/web-issues#1448
> [1448] fix: what is posts translation in reviews

- assets/styles/pages/TrialRedesign.scss
I added styles for class rtl and rewrite styles
**Checklist**
Close QualityUnit/web-issues#1169
> [1169] Visual bug on Arabic Trial Page 

- templates/header.php
I added urlslab-skip-all class to header for language switcher
**Checklist**
Close QualityUnit/web-issues#2457
> [2457] LA articles open in new tab

- functions/compact-header.php
- functions/metaboxes.php
- lib/custom-blocks/compact-header.php
- lib/metaboxes/cta-button.php
- lib/metaboxes/signup-sidebar.php
- lib/shortcodes/signup-sidebar.php
- template-blog-header.php
- templates/content-single-ms_academy.php
- templates/content-single-ms_glossary.php
- templates/content-single-ms_templates.php
- templates/content-single.php
I added a new cta button to the compact header and simplified the code for the other buttons in the header
**Checklist**
Close QualityUnit/web-issues#2393
> [2393] NEW CTA fo LA

- assets/styles/components/SignupSidebar.scss
- functions.php
- functions/get-cta-button-data.php
- lib/shortcodes/signup-sidebar.php
- template-blog-header.php
- template-blog.php
- templates/content-single-ms_academy.php
- templates/content-single-ms_glossary.php
- templates/content-single-ms_templates.php
- templates/content-single.php
Editing the logic of the button and adding default texts and links for the button and fixing a couple of visual bugs
**Checklist**
Close QualityUnit/web-issues#2393
> [2393] NEW CTA BUTTON for LA

- assets/styles/components/UrlslabTOC.scss
- functions/components-imports.php
styling for urlslab toc module
Close QualityUnit/web-issues#2462
> [2462] feat: styling for urlslab toc module

- lib/shortcodes/signup-form-simple.php
i added text to simple form template. 
**Checklist**
Close QualityUnit/web-issues#2492
> [2492] Edit simple form 

- functions/metaboxes.php
- lib/metaboxes/custom-urls.php
- templates/content-archive-ms_features.php
I Added a metabox for entering custom URLs in the post type archive
**Checklist**
Close QualityUnit/web-issues#2495
> [2495] Added a field for entering custom URLs in the archives

- functions/get-posts.php
- lib/metaboxes/features.php
- templates/content-archive-ms_features.php
ability to add custom integrations to features archive
Close QualityUnit/web-issues#2265
> [2265] feat: ability to add custom integrations to features archive

- assets/scripts/app/app.js
- assets/styles/Elementor.scss
- assets/styles/app.scss
- assets/styles/components/_TrialStickyButton.scss
- templates/footer.php
I added new trial button with animations and edit animations of the contact us button
**Checklist**
Close QualityUnit/web-issues#1327
> [1327] added new pinned trial button

- functions/metaboxes.php
- lib/metaboxes/custom-urls.php
I added a metabox for custom urls 
**Checklist**
Close QualityUnit/web-issues#2495
> [2495] Added metabox for custom urls for features

- templates/content-archive-ms_features.php
Fixed bad links and add support for pillar item
**Checklist**
Close QualityUnit/web-issues#2495
> [2495] Fixed bad links in data href and add to pillar element

- functions/redirects.php
I added function for redirect videos categories
**Checklist**
Close QualityUnit/web-issues#2531
> [2531] Added redirect for videos categories

- templates/content-single-ms_integrations.php
I replaced h2 title "Partner" with post title + "integration"
**Checklist**
Close QualityUnit/web-issues#2580
> [2580] Incorrect H2 "Partner" on integration posts LA

- base-scripts.php
I deleted customer success pages from condition for chat button
**Checklist**
Close QualityUnit/web-issues#1506
> [1506] Wrong Chat Button on Some Customer Success Pages

- assets/styles/layouts/Header.scss
I removed styles for hover effect from subitems in desktop menu and ad styles for admin bar
**Checklist**
Close QualityUnit/web-issues#2593
> [2593] Removed hover effect on sub items in desktop menu

- assets/styles/components/FeaturesTable-New.scss
redesign problematic element use in /tour and /call-center-software
Close QualityUnit/web-issues#2132
> [2132] feat: redesign element

- assets/styles/common/_global.scss
- assets/styles/layouts/Header.scss
- lib/assets.php
- template-blog-header.php
I removed the style "content-visibility: auto;" from the registration form and I removed the css import from the head to the body because some styles override those styles.
**Checklist**
Close QualityUnit/web-issues#2594
> [2594] LA trial form cuting text

- assets/styles/components/_ContactUs.scss
I added fallback for gradient css.  
**Checklist**
Close QualityUnit/web-issues#1327
> [1327] Added fall back for css gradient

- assets/scripts/app/tooltips.js
- lib/shortcodes/signup-form.php
- template-trial-redesign.php
- template-trial.php
I replaced new text for trial forms and fixed bugged tooltips in forms
**Checklist**
Close QualityUnit/web-issues#2618
Close QualityUnit/web-issues#2594
> [2618] Changing duration of trials

- assets/styles/components/BlogTopPost.scss
- assets/styles/layouts/_Blog.scss
- templates/content-archive.php
i fixed broken filtering and adding new logic for top post on the blog archive page after remake slider to static top post.
**Checklist**
Close QualityUnit/web-issues#2545
Close QualityUnit/web-issues#2622
> 2545 fixed broken filtering and fix duplicated posts in the blog

- assets/scripts/app/toggleVisibility.js
- assets/styles/components/_ContactUs.scss
I rewrote and refactored the JS code for the Contact Us button to work better. And added some styles for better animations.
**Checklist**
Close QualityUnit/web-issues#2626
> [2626] ContactUS button working incorrectly on LA 

- assets/scripts/app/toggleVisibility.js
- assets/styles/components/_ContactUs.scss
I optimized the animations and styles in the Contact Us button
**Checklist**
Close QualityUnit/web-issues#2626
> [2626] Optimizing the animations in the contact us button

- assets/styles/shortcodes/VideoTranscript.scss
Only add display: none on <br> elements 
**Checklist**
Close QualityUnit/web-issues#2628
> [2628] The video transcript feature has a broken design

- assets/styles/components/AnnouncementBar.scss
- assets/styles/components/DemoBar.scss
- assets/styles/layouts/tests/RequestDemo.scss
- functions/header-banners.php
- lib/widgets/qu-checklists/package.json
- lib/widgets/qu-checklists/src/components/CheckListItem.js
- lib/widgets/qu-checklists/src/components/Editor.js
- lib/widgets/qu-checklists/src/edit.js
- lib/widgets/qu-checklists/src/edit_checklistitem.js
- lib/widgets/qu-checklists/src/frontend.js
- lib/widgets/qu-checklists/yarn.lock
Fixing responsivity and cutted background of banners and demo
Close QualityUnit/web-issues#2523
Close QualityUnit/web-issues#1556
Close QualityUnit/web-issues#2648
> [2523] I2523 1556 fixes

- assets/styles/components/DemoBar.scss
- assets/styles/shortcodes/VideoTranscript.scss
I changed styles for the video transcritp element and fix some small bug on the demo bar element
**Checklist**
Close QualityUnit/web-issues#2628
Close QualityUnit/web-issues#2654
> [2628] Chaned styles for video transcript and increase z index on demo bar

- templates/header.php
I hiding ai announcement bar for now
**Checklist**
> feat: hiding ai banner

- functions/import-functions.php
- templates/header.php
I reverted the old feature to work properly
**Checklist**
Close QualityUnit/web-issues#2660
> [2660] Broken sign up banner on LA

- lib/widgets/qu-checklists/src/components/CheckListItem.js
- lib/widgets/qu-checklists/src/components/Editor.js
- lib/widgets/qu-checklists/src/edit.js
- lib/widgets/qu-checklists/src/edit_checklistitem.js
- lib/widgets/qu-checklists/yarn.lock
- lib/widgets/qu-commonproblems/src/components/Editor.js
- lib/widgets/qu-expertnote/src/components/Editor.js
- lib/widgets/qu-howtos/src/components/Editor.js
- lib/widgets/qu-howtos/yarn.lock
editing checklists formatting fix (for how to items too)
Close QualityUnit/web-issues#2662
> [2662] fix: editing checklists

- assets/scripts/app/toggleVisibility.js
I replaced the new one with the old one because it didn't work properly. 
**Checklist**
Close QualityUnit/web-issues#2682
> [2682]: Switch between Support team view / Customer view is not working properly

- assets/styles/components/AiAssistantPricing.scss
- assets/styles/components/AnnouncementBar.scss
- functions/import-functions.php
- templates/header.php
I enabled ai assistant promo banner on the home page and i changed some small css for him
**Checklist**
Close QualityUnit/web-issues#2635
> [2635] Enabled announcement bar with ai assistant promo

- .github/workflows/build-test-qu-checklists.yml
- .github/workflows/build-test-qu-commonproblems.yml
- .github/workflows/build-test-qu-expertnote.yml
- .github/workflows/build-test-qu-howtos.yml
- .github/workflows/build-test-qu-reviews.yml
- .github/workflows/build-test-qu-usecase.yml
- .github/workflows/build-test-statistics.yml
- .github/workflows/build-test-typing-test.yml
- .github/workflows/build-test-web-calc-featured.yml
- .github/workflows/build-test-web-calc.yml
- .github/workflows/build-test.yml
- .github/workflows/eslint.yml
- .github/workflows/stylelint.yml
- apps/typing-test/README.md
- apps/web-calc-featured/README.md
- apps/web-calc/README.md
- lib/widgets/qu-banners/banners.php
- lib/widgets/qu-checklists/checklists.php
- lib/widgets/qu-commonproblems/commonproblems.php
- lib/widgets/qu-expertnote/expertnote.php
- lib/widgets/qu-howtos/howtos.php
- lib/widgets/qu-reviews/reviews.php
- lib/widgets/qu-usecase/usecase.php
- lib/widgets/statistics/statistics.php
> chore: upgrade nodejs

- assets/styles/components/AnnouncementBar.scss
- templates/header.php
I hid the announcement bar
**Checklist**
Close QualityUnit/web-issues#2635
> [2635]  Hiding announcement bar on LA

- lib/widgets/qu-banners/src/components/Editor.js
- lib/widgets/qu-banners/src/scss/editor.scss
- lib/widgets/qu-checklists/src/scss/editor.scss
Added white background to toolbar
Close QualityUnit/web-issues#2662
> [2662] fix: toolbar in checklists white

- apps/typing-test/src/style.css
Changing text color in typing test to be darker
Close QualityUnit/web-issues#2383
> [2383] fix: text color in typing test

- assets/styles/components/_GoodHands.scss
- assets/styles/layouts/Footer.scss
- elementor.php
- front-page.php
- lib/shortcodes/good-hands.php
- template-free-account.php
moving new good hands to bottom, removing old one
Close QualityUnit/web-issues#1412
> [1412] fix: moving new good hands to bottom, removing old one

- assets/styles/components/_Block.scss
> fix: class irelevantly used in front page element

- assets/styles/components/Signup.scss
- assets/styles/components/SignupSidebar.scss
I added styles for inputs in signup forms
**Checklist**
> Fixed styles for inputs in signup forms

- assets/styles/components/SidebarItemsSlider.scss
- templates/content-single-ms_checklists.php
Removed styles for fixed position on the sidebar slider
**Checklist**
Close QualityUnit/web-issues#2719
> [2719] Remove pin to "other marketing checklist" element

- assets/styles/components/AlternativeTable.scss
Added style to make the table scrollable
**Checklist**
Close QualityUnit/web-issues#2751
> [2751] Table overlapping with side trial banner

- templates/content-archive-ms_academy.php
- templates/content-archive-ms_features.php
- templates/content-archive-ms_templates.php
I removed spaces from link for bgs on the archives academy, templates and features
**Checklist**
> Removed spaces from link for bgs

- assets/styles/elements/_Form.scss
- assets/styles/layouts/_Custom.scss
i added styles for input element and some styles for custom html signup form
**Checklist**
Close QualityUnit/web-issues#2784
> [2784] Missing design of Affiliate signup form at www.liveagent.com/affiliate-program/affiliate-signup/

- assets/styles/components/DemoBar.scss
- assets/styles/components/_HeaderLanguageSwitcher.scss
- assets/styles/layouts/Header.scss
I edited transitions for demo bar so that it does not jump when loading the website for 1ms and added some styles for header for better CLS parameter
**Checklist**
Close QualityUnit/web-issues#2802
> [2802] Fix loading of Schedule banner

- assets/scripts/app/signup_login_js_loader.js
- assets/scripts/custom/filterMenu.js
- assets/scripts/static/crm.js
- assets/styles/components/Signup.scss
- assets/styles/pages/TrialRedesign.scss
- lib/shortcodes/signup-form.php
Added selection of regions to Trial signup form.
Updated `FilterMenu` to work as simple select, at least for purpose of this issue for now.
Updated crm script to be able work with and validate data from selections too.
Updated signup loader js to run crm script also on events dispatched by selection. 
Close QualityUnit/web-issues#2054
> Trial signup regions

- assets/styles/layouts/_PricingPrograms.scss
Added width for element in the pricing page
**Checklist**
Close QualityUnit/web-issues#2803
> [2803] Curropted design in pricing for firefox

- assets/styles/shortcodes/IntroductionVideos.scss
Fixed border in introduction tabs in signup installation progress.
> fix: signup install introduction tabs border

- assets/styles/components/_Login.scss
- assets/styles/layouts/tests/RequestDemo.scss
Close QualityUnit/web-issues#1625
Close QualityUnit/web-issues#1556
> fix: demo,login

- assets/styles/common/_global.scss
I removed content visibility  styles for content on the help desk page
**Checklist**
> Correction of bad loading of content on the helpdesk page

- functions/content-filters.php
duplicate hreflang and remove rel next and prev
**Checklist**
> fix: duplicate hreflang and remove rel next and prev

- assets/styles/components/Table.scss
- functions/content-filters.php
- templates/content-archive-ms_reviews-posts.php
- templates/content-single-ms_reviews-top.php
- templates/content-single-ms_reviews.php
Fixess eviews schema, table max width
Close QualityUnit/web-issues#2828
> [2828] fix: reviews schema, table max width

- lib/shortcodes/signup-form-free.php
I changed h1 element to h2 
**Checklist**
Close QualityUnit/web-issues#2832
> [2832] Changed h1 title to h2

- assets/scripts/custom/custom_lightbox.js
- assets/scripts/custom/custom_lightbox_youtube.js
> fix: body selector

- assets/styles/elements/_Button.scss
- assets/styles/elements/_Typography.scss
- base.php
- functions/components-imports.php
- lib/cleaner/assets.php
> Pagespeed fix v2

- assets/styles/components/_HeroBanner.scss
- assets/styles/components/_Login.scss
- assets/styles/layouts/Header.scss
- assets/styles/pages/TrialRedesign.scss
- assets/styles/shortcodes/HeroBannerAwards.scss
- lib/shortcodes/hero-banner-awards.php
- template-trial-redesign.php
new awards in trial, pagespeed fixes to login and header formatting
Close QualityUnit/web-issues#2852
> [2852] feat:  new awards in trial, pagespeed fixes to login and header format

- assets/scripts/app/signup_login_js_loader.js
- assets/scripts/custom/responsiveTable.js
- assets/styles/Elementor.scss
- assets/styles/app.scss
- assets/styles/components/Table.scss
- assets/styles/components/_AlternativeTable.scss
- assets/styles/components/_TrialStickyButton.scss
- functions/components-imports.php
Fixes som pagespeed optimalizations bugs
Close QualityUnit/web-issues#2856
> Pagespeed fixes v3

- assets/styles/components/AnnouncementBar.scss
> fix: announcement bar at the top

- templates/content-single-ms_reviews.php
I Rearranged loading scripts in reviews to fix gallery
**Checklist**
> Rearranged loading scripts in reviews to fix gallery

- .github/workflows/publish-release.yml
publish script to node 20
Close QualityUnit/web-issues#2863
> [2863] fix: publish script to node 20

- assets/styles/components/Table.scss
I added only overflow-x on scroll for fix overlaping table
**Checklist**
Close QualityUnit/web-issues#2856
> [2856] Table overlap

- templates/footer.php
hiding good hands banner in other languages
Close QualityUnit/web-issues#2876
> [2876] fix: hiding good hands banner in other languages

- assets/styles/shortcodes/BlockPricing.scss
I set only one margin-left from auto to 0 for better responsivity
**Checklist**
Close QualityUnit/web-issues#2871
> [2871] New Alternatives page broken

- functions.php
- functions/import-functions.php
- templates/content-archive.php
temporary fix for blog css loading
Close QualityUnit/web-issues#2887
> [2887] blog css defer fix

- assets/styles/components/_ContactUs.scss
- base-scripts.php
replacing contact form with chatbot on selected pages
Close QualityUnit/web-issues#2885
> [2885] feat: replacing contact form with chatbot on selected pages

- assets/styles/shortcodes/BlockPricing.scss
- functions.php
- functions/components-imports.php
- functions/import-functions.php
- lib/assets.php
- lib/shortcodes/alternatives.php
- lib/widgets/statistics/statistics.php
- templates/content-archive-ms_alternatives.php
- templates/content-archive-ms_reviews-posts.php
- templates/content-archive.php
Fixes CSS loading to footer in case of elementor, forces load of content blocks to head, blinking of Blog and Alternatives shortcode
Close QualityUnit/web-issues#2883
Close QualityUnit/web-issues#2887
Close QualityUnit/web-issues#2894
> fix: #2883, #2887, #2894

- assets/styles/components/_GoodHands.scss
- assets/styles/pages/TrialRedesign.scss
- assets/styles/shortcodes/HeroBannerAwards.scss
- base-scripts.php
- contactus-box.php
chatbot loading in contact form, awards badges cut
Close QualityUnit/web-issues#2885
Close QualityUnit/web-issues#2852
> [2885] fix: chatbot loading in contact form, awards badges cut

- assets/scripts/custom/awardsInfiniteScroll.js
- assets/styles/layouts/_Awards.scss
- lib/post-types/awards.php
- lib/shortcodes/awards.php
- templates/content-archive-ms_awards.php
I added new archive for awards, added infinity scroll for this archive and styles.
**Checklist**
> [2741] Added new archive for awards page

- assets/images/play_button.svg
- assets/styles/layouts/_Webinars.scss
- assets/styles/pages/Webinars.scss
- functions/metaboxes.php
- functions/post-types.php
- functions/redirects.php
- lib/metaboxes/webinars.php
- lib/post-types/webinars.php
- templates/content-archive-ms_webinars.php
I created new postype webinars and create template for archive.
**Checklist**
> 2741 Create new postype webinars

- assets/styles/elements/_Typography.scss
I edited h4 and h3 headings bigger on the mobile
**Checklist**
Close QualityUnit/web-issues#2902
> [2902] make h4 and h3 headings bigger on the mobile

- templates/content-archive-ms_awards.php
Fixed case sensitive problem
**Checklist**
> [2741] Fixed case sensitive error

- assets/styles/elements/_Typography.scss
added new style for numbered list
Close QualityUnit/web-issues#1616
> [161] fix: added new style for numbered list

- assets/styles/components/AffiliateSignup.scss
small safari bugfixes
Close QualityUnit/web-issues#1616
> [1616] fix: small safari bugfixes

- assets/scripts/custom/awardsInfiniteScroll.js
- functions/rest-api.php
- lib/rest-api/get-awards-posts.php
I extend the rest api and then pulling the data to the frontend
**Checklist**
> [2741] Fixed js for infinity loop on awards archive

- assets/scripts/custom/awardsInfiniteScroll.js
- lib/rest-api/get-awards-posts.php
Replaced default rest api and then pulling the data to the frontend for awards archive
**Checklist**
> [2741] Replaced default rest api and then pulling the data to the frontend

- assets/scripts/custom/awardsInfiniteScroll.js
- lib/rest-api/get-awards-posts.php
I rewrote the endpoint for awards
**Checklist**
> Rewroted the endpoint for awards

- assets/styles/components/_ContactUs.scss
- composer.lock
- contactus-box.php
checking status of servers in contact us menu
Close QualityUnit/web-issues#2021
> [2021] contact us status

- assets/scripts/static/crmInstaller.js
- lib/trial-signup/class-trial-signup.php
crm signup response data read from cookie by js
Close QualityUnit/web-issues#2926
> I2926 trial signup cookie

- assets/scripts/app/app.js
Added conditions for language switcher
**Checklist**
Close QualityUnit/web-issues#2925
> [2925] Cookie notification not working on ru.liveagent.com

- assets/scripts/static/crmCaptcha.js
- assets/scripts/static/crmForms.js
- assets/scripts/static/crmInstaller.js
- lib/shortcodes/signup-form-free.php
- lib/shortcodes/signup-sidebar.php
- lib/trial-signup/class-trial-signup.php
-- tracking scripts sent on installation page only when crm api respond that installation really starts
-- fixed caching issues, current captcha key/version read via javascript, inline javascript from php moved to standalone `crmCaptcha` file.
Close QualityUnit/web-issues#2931
> Trial signup corrections

- lib/trial-signup/class-trial-signup.php
hot fix, changed langcode `ar-SA` to `ar-sa`
> fix: fixed ar-sa language code

- assets/styles/common/_mixins.scss
- assets/styles/components/AffiliateSignup.scss
affiliate program signup scrollbar
Close QualityUnit/web-issues#1616
> [1616] fix: affiliate program signup scrollbar

- assets/scripts/static/crmInstaller.js
- lib/shortcodes/signup-form-free.php
- lib/shortcodes/signup-form-redeemcode.php
- lib/shortcodes/signup-form.php
- lib/shortcodes/signup-sidebar.php
- lib/trial-signup/class-trial-signup.php
Fixed capterra tracking script source.
Fixed caching issues caused by unnecessary wp nonce check.
Close QualityUnit/web-issues#2949
> I2949 capterra tracking

- assets/styles/components/BoxesDotted.scss
- assets/styles/components/_BlockStartups.scss
- assets/styles/pages/Startups.scss
- assets/styles/shortcodes/BlockBadges.scss
- assets/styles/shortcodes/BlockPricing.scss
- lib/shortcodes/block-pricing.php
I rewrote elements and their styles on the startups page for correct view
**Checklist**
Close QualityUnit/web-issues#2893
> [2893] Fixing styles for startup page

- templates/content-single-ms_directory.php
changed link for tag in compact header on the directory
**Checklist**
Close QualityUnit/web-issues#2948
> [2948] Changing link in header tag

- apps/web-calc-featured/src/assets/style/layouts/_Main.scss
- apps/web-calc/src/assets/style/layouts/_Main.scss
- assets/styles/common/_elementor.scss
- assets/styles/common/_global.scss
- assets/styles/common/elementor-custom.scss
- assets/styles/components/Block.scss
- assets/styles/components/BlockVideo.scss
- assets/styles/components/Boxes.scss
- assets/styles/components/BoxesStars.scss
- assets/styles/components/IconTabs.scss
- assets/styles/components/Signup.scss
- assets/styles/components/Table.scss
- assets/styles/components/_GoodHands.scss
- assets/styles/components/_HeroHeadlineBanner.scss
- assets/styles/components/_HorizontalTabs.scss
- assets/styles/elements/_Button.scss
- assets/styles/elements/_Typography.scss
- assets/styles/layouts/HelpDesk.scss
- assets/styles/shortcodes/BlockPricing.scss
- functions/content-filters.php
- lib/shortcodes/signup-sidebar.php
- template-academy-header.php
- template-academy.php
- template-blog-header.php
- templates/content-single-ms_success-stories.php
Fixes to responsivity and CLS
Close QualityUnit/web-issues#2950
Close QualityUnit/web-issues#2951
> [2950] responzivity fixes

- assets/styles/components/_AlternativeTable.scss
I added styles for icons in the alternatives table
**Checklist**
Close QualityUnit/web-issues#2944
> [2944] Missing icons with tooltips

- assets/styles/shortcodes/BlockPricing.scss
fixing styles on the startup page
**Checklist**
Close QualityUnit/web-issues#2893
> 2893 fixing styles on the startup page

- assets/styles/Elementor.scss
- assets/styles/components/RequestForProposalHero.scss
- functions/shortcodes.php
- lib/shortcodes/request-for-proposal-form.php
I redesigned request for proposal page. New formular from support.quality.com styles for him and styles for new section
**Checklist**
Close QualityUnit/web-issues#1411
> [1411] Redesign of Request for Proposal Page

- assets/scripts/custom/research_post.js
i removed js code for modifying h1 element on the research single page
**Checklist**
Close QualityUnit/web-issues#2834
> [2834] Don't modify the H1 tag with JavaScript

- assets/styles/Elementor.scss
- assets/styles/components/RequestForProposal.scss
- lib/shortcodes/request-for-proposal-form.php
I added some styles for this page and change scrpit for form from support.qualityunit.com
**Checklist**
Close QualityUnit/web-issues#1411
> [1411] fixed some styles and changed script for form

- lib/shortcodes/slider-testimonials-home.php
I set default attribute in the shortcode for testimonial slider
**Checklist**
Close QualityUnit/web-issues#2967
> [2967] set default attribute in the shortcode for testimonial slider

- assets/styles/Elementor.scss
- assets/styles/components/Reference.scss
- assets/styles/components/Reviews.scss
fixed styles for reviews reference
**Checklist**
Close QualityUnit/web-issues#2966
> [2966] fixed styles for reviews reference

- assets/styles/common/_global.scss
- assets/styles/common/elementor-custom.scss
- assets/styles/components/Block.scss
- assets/styles/components/BlockLearnMore.scss
- assets/styles/components/BlogTopPost.scss
- assets/styles/components/FeaturesTable-New.scss
- assets/styles/components/IconTabs.scss
- assets/styles/components/_CategoryItem.scss
- assets/styles/components/_CookieBar.scss
- assets/styles/components/_GoodHands.scss
- assets/styles/components/_SignupSidebar.scss
- assets/styles/elements/_ResearchBlock.scss
- assets/styles/layouts/_Post.scss
- assets/styles/layouts/_PricingPrograms.scss
- assets/styles/layouts/_Research.scss
- assets/styles/shortcodes/BlockPricing.scss
- lib/shortcodes/signup-sidebar.php
- templates/head.php
Visual and mobile glitches, CLS fix for use cases
Close QualityUnit/web-issues#2974
> Visual glitches fixes

- assets/styles/Elementor.scss
- assets/styles/app.scss
- assets/styles/common/common.scss
- assets/styles/pages/Directory.scss
- contactus-box.php
- functions/header-banners.php
- lib/cleaner/assets.php
- templates/content-archive-ms_directory.php
- templates/content-archive-ms_glossary.php
- templates/content-single-ms_directory.php
- templates/head.php
Improving CLS on multiple sections, conditionally loading whole chatbot script on contact us button
Close QualityUnit/web-issues#2976
> [2976] feat: optimizing cls and ranking performance

- lib/shortcodes/request-for-proposal-form.php
I removed trustpilot logo from request for proposal page
**Checklist**
> Removed trustpilot logo from request for proposal page

- lib/shortcodes/awards-badges.php
added attribute to element for testing on dev
**Checklist**
> Added attribute  to element for testing on dev

- functions/dynamic-award-badges.php
added code for selecting awards only from the current language
**Checklist**
> Added code for selecting awards only from the current language

- assets/styles/components/RequestForProposal.scss
- lib/shortcodes/request-for-proposal-form.php
- template-redeem-code.php
- template-trial-redesign.php
Removed logo get app from components
**Checklist**
> Removing logo get app

- templates/content-archive.php
I added a feature to display the top post with the category displayed on the right. Because when you filtered it displayed the top post from another category and that didn't make sense
**Checklist**
Close QualityUnit/web-issues#2979
> [2979] Blog categories issues 

- assets/styles/app.scss
I added newBadge css file to styles for pages which don't have elementor
**Checklist**
Close QualityUnit/web-issues#2983
> [2983] Label new in main menu stopped to work

- templates/content-single-ms_academy.php
- templates/content-single-ms_features.php
- templates/content-single-ms_glossary.php
- templates/content-single-ms_templates.php
- templates/content-single-ms_videos.php
- templates/content-single.php
I added css files to single pages templates for lightbox support
**Checklist**
Close QualityUnit/web-issues#2984
> [2984] LA Features pages image expand

- lib/trial-signup/class-trial-signup.php
I removed the Norwegian domain from the condition for deactivating the trial form. Now the trial form works like on other language mutations
**Checklist**
Close QualityUnit/web-issues#2988
> [2988] Fix Trial variation for liveagent.no

- templates/content-archive.php
i added condition for fix warning
**Checklist**
Close QualityUnit/web-issues#2993
> [2993] Fix PHP Warning

- assets/styles/components/Reference.scss
I changed image suffix from svg to png and add some style fixes.
**Checklist**
Close QualityUnit/web-issues#2989
> [2989] Missing image in the reference element

- lib/trial-signup/class-trial-signup.php
Make sure the posted data are type of string before sent to validation. Any other type of data is not correct user input.
Close QualityUnit/web-issues#2996
> fix: ensure posted data are type of string

- lib/custom-blocks/compact-header.php
- template-free-account.php
- templates/content-single-ms_features.php
- templates/content-single-ms_glossary.php
- templates/content-single.php
I added missing attributes for the validate rich results. 
**Checklist**
Close QualityUnit/web-issues#2990
> [2990] Try to fix Rich Results Validation fails

- assets/styles/components/RequestForProposal.scss
- assets/styles/layouts/FreeAccount.scss
- template-free-account.php
I rewrote some style for fix visual bugs.
**https://www.liveagent.com/startups/#signupform -> weird opacity block**
I skipped this element in issue because is larger issue. I make new PR for this element.
**Checklist**
Close QualityUnit/web-issues#2994
> [2994] Fixing web visual bugs

- assets/styles/pages/TrialRedesign.scss
i hid awards on devices which have resolution less then 1550px.
**Checklist**
Close QualityUnit/web-issues#2997
> [2997] Trial signup - badges

- lib/trial-signup/class-trial-signup.php
Fixed undefined POST variable.
Close QualityUnit/web-issues#3002
> fix: catch undefined post value

- templates/content-single-ms_features.php
I added code for the display other plans tags
**Checklist**
Close QualityUnit/web-issues#3007
> [3007] Feature "available in" doesn't show all plans

- lib/custom-blocks/compact-header.php
I added condition. If is single page directory and author page so set `itemprop="name"` otherwise `itemprop="headline"`  as the schemes require
**Checklist**
Close QualityUnit/web-issues#3013
> [3013] Structured data has schema.org validation error on Directories

- assets/styles/Elementor.scss
- templates/header.php
I replaced new title for AI assistant 
**Checklist**
> fix: changed title in the announcement bar

- assets/styles/components/ExitPopup.scss
- templates/footer.php
I added a class for urlslab skip all and changed styles for better visual
**Checklist**
Close QualityUnit/web-issues#3025
> [3025] Edit exit popup styles

- assets/scripts/custom/exitPopup.js
- assets/styles/components/ExitPopup.scss
- templates/footer.php
Debug exit popup on the firefox
**Checklist**
Close QualityUnit/web-issues#3025
> [3025] Debug exit popup on the firefox

- assets/scripts/custom/exitPopup.js
- templates/footer.php
added JS code to save cookies after clicking the button
**Checklist**
Close QualityUnit/web-issues#3025
> [3025] added JS code to save cookies after clicking the button

- lib/setup.php
I removed trial button from the footer
**Checklist**
Close QualityUnit/web-issues#3027
> [3027] Remove trial button from footer

- templates/header.php
I added condition for hidden header banner on the other languages as EN 
**Checklist**
> Hidding header banners on the other languages as en

- assets/styles/components/_HeroHeadlineBanner.scss
I added one style for fix play button img
**Checklist**
Close QualityUnit/web-issues#3028
> [3028] Fix tour video button

- assets/scripts/custom/IconTabs.js
- assets/styles/components/IconTabs.scss
I was editing an element and it was necessary to replace the gif image. I replaced it with an SVG image and animated it with JS.
**Checklist**
Close QualityUnit/web-issues#3029
Close QualityUnit/web-issues#2994
> [3029] Fixes to statistics element

- package.json
- yarn.lock
Reverting back to Gulp 4 as 5 cause build failure
Close QualityUnit/web-issues#3050
> [3050] fix: gulp version revert back to 4

- base-scripts.php
- contactus-box.php
I replaced urlslab chat with flowhunt chatbot
**Checklist**
Close QualityUnit/web-issues#3054
> [3054] Use flowhunt chatbot everywhere

- base-scripts.php
- contactus-box.php
I edited the script for the chatbot that was loaded every time the contact us button was clicked
**Checklist**
> Editing the script for the chatbot - it loads in circles

- templates/content-archive-ms_videos.php
- templates/content-single-ms_academy.php
- templates/content-single-ms_alternatives.php
- templates/content-single-ms_checklists.php
- templates/content-single-ms_directory.php
- templates/content-single-ms_features.php
- templates/content-single-ms_glossary.php
- templates/content-single-ms_integrations.php
- templates/content-single-ms_research.php
- templates/content-single-ms_reviews.php
- templates/content-single-ms_templates.php
- templates/content-single-ms_videos.php
- templates/content-single.php
Add AI overview back
**Checklist**
> feat: add ai overview back

- assets/styles/elements/_PostTypography.scss
I rewrote the styles for the lists because after updating gutenberg the list has a new class
**Checklist**
Close QualityUnit/web-issues#3088
> 3088 Lists not working on all webs

- functions/sidebar-toc.php
no h3 in compact header
Close QualityUnit/web-issues#3056
> [3056] fix: no h3 in compact header

- elementor.php
- templates/content-page.php
Added condition to page templates as is Elementor page and basic wordpress page
**Checklist**
Close QualityUnit/web-issues#3135
> [3135] Hide title "Related articles" if empty on elementor and page temaplates

- assets/scripts/app/queryParamsToUrls.js
adds query params to every liveagent url on webpage
Close QualityUnit/web-issues#3019
> [3019] feat: adds query params to every liveagent url on webpage

- base-scripts.php
Changed query version in script for ai chatbot
**Checklist**
> Changed query version in script for ai chatbot

- assets/scripts/app/queryParamsToUrls.js
I'm adding a blacklist to exclude some parameters from the JS function for adding parameters to URLs.
and added a condition to check if I'm on the admin.liveagent.com domain because we don't need to add parameters to the developer website
**Checklist**
Close QualityUnit/web-issues#3162
> [3162] Blacklist some parameters which are not forwarded to other links

- assets/styles/components/_ContactUs.scss
- contactus-box.php
I added elements and styles for status labels.
**Checklist**
Close QualityUnit/web-issues#3091
> [3091] Service status degradation not shown in the contact multi-widget on website

- assets/styles/layouts/Footer.scss
- templates/footer.php
I added new column to footer with G2 script for reviews
**Checklist**
Close QualityUnit/web-issues#3180
> [3180] Revalidate Schema.org definition

- templates/footer.php
added class `urlslab-skip-all` to reviews in the footer 
**Checklist**
> added condition for the loading only on elementor page

- template-free-account.php
i replaced new text
**Checklist**
Close QualityUnit/web-issues#3163
> [3163] Wrong information on the "Create free account" page

- assets/styles/layouts/Footer.scss
- templates/footer.php
i removed reviews from footer
**Checklist**
Close QualityUnit/web-issues#3209
> [3209] Implement our own custom footer star rating with Schema.org markup

- contactus-box.php
i added variable `$en_slug` for initialized before we use it
**Checklist**
Close QualityUnit/web-issues#3195
> [3195] Undefined variable $en_slug in contactus-box.php

- assets/styles/layouts/_Post.scss
I fixed styles for post buttons
**Checklist**
Close QualityUnit/web-issues#3204
> [3204] Fix Footer allignments

- templates/header.php
I removed announcement banner from the pricing page
**Checklist**
Close QualityUnit/web-issues#3240
> [3240] Remove Cross-Selling Banner / Pop-up

- assets/styles/elements/_LabelTag.scss
Fixed styles for safari browser
**Checklist**
Close QualityUnit/web-issues#3239
> [3239] Pricing tag is displayed incorrectly

- templates/footer.php
I added script to footer because we need him on the whole website.
**Checklist**
Close QualityUnit/web-issues#3186
> [3186] Element does not work in incognito mode

- assets/styles/common/_variables.scss
- assets/styles/elements/_BadgeNew.scss
- assets/styles/elements/_LabelTag.scss
- assets/styles/layouts/_ComparePlansNew.scss
- assets/styles/layouts/_PricingPrograms.scss
- assets/styles/layouts/_PricingTop.scss
I changed pricing page according to the new design.
**Checklist**
Close QualityUnit/web-issues#3606
> [3606] Discount Promotion on All Plans for LiveAgent 

- assets/styles/layouts/_ComparePlansNew.scss
- assets/styles/layouts/_PricingPrograms.scss
fixed colors on the pricing page
**Checklist**
> fix: price color on the pricing page

- assets/styles/layouts/_ComparePlansNew.scss
I hid the free plan instead of enterprise
**Checklist**
Close QualityUnit/web-issues#3606
> [3606] Hidding free plan in the compare planes

- assets/scripts/custom/sidebar_toc.js
I improved JS for TOC and fixed lazyloading on pages where there is a TOC slider.
**Checklist**
Close QualityUnit/web-issues#3220
> [3220] Verify why is lazy loading not working in Elementor pages

- assets/styles/layouts/_PricingPrograms.scss
modified the first banner and improved the banner code. More universal and better for languages ​​with long words
**Checklist**
Close QualityUnit/web-issues#3257
> [3257] Reinstate former Free Account element for Demo Call booking

- assets/scripts/static/crmInstaller.js
- base-scripts.php
I added a new conversion event for the try button and renamed the old event to better compare the two events
**Checklist**
Close QualityUnit/web-issues#3250
> [3250] LiveAgent Google Ads conversion action is not working properly

- assets/styles/components/compactHeader.scss
I added space around the elements and increased font size on the mobile 
**Checklist**
Close QualityUnit/web-issues#3201
> [3201] Increase the size of elements to make them easier to use on mobile

- base-scripts.php
chatbot input placeholder translate
Close QualityUnit/web-issues#3177
> [3177] chatbot input placeholder translate

- apps/web-calc-featured/src/data/alternatives.json
- apps/web-calc/src/data/alternatives.json
- lib/shortcodes/block-pricing.php
- template-free-account.php
I changed prices of the small plans
**Checklist**
Close QualityUnit/web-issues#3279
> [3279] Pricing changes

- assets/styles/Elementor.scss
- assets/styles/components/_ReviewsAwards.scss
- functions.php
return back style for review awards
Close QualityUnit/web-issues#3133
> [3133] fix: return back style for review awards

- base-scripts.php
Hotfix for not working chatbot
> fix: chatbot not working

- assets/styles/components/BlockCoupon.scss
- lib/shortcodes/countdown.php
I changed a couple of styles in the block coupon element
**Checklist**
Close QualityUnit/web-issues#3688
> [3688] Black Friday / Cyber Monday promotion 2024

- templates/header.php
I removed announcement bar from header because this banner make high parameters in the google metrtics - it was a management decision
**Checklist**
Close QualityUnit/web-issues#3219
> [3219] Remove announcement banner from header

- assets/i18n/g2-reviews/g2-reviews.json
I added type "@Offer" witch all pricing plans to the schema.
**Checklist**
Close QualityUnit/web-issues#3209
> [3209] added pricing plans to the schema as offer parameter

- assets/styles/components/_Login.scss
- assets/styles/pages/TrialRedesign.scss
- base-scripts.php
- functions/components-imports.php
- lib/shortcodes/login.php
- lib/shortcodes/request-for-proposal-form.php
- lib/shortcodes/signup-form-free.php
- lib/shortcodes/signup-form-redeemcode.php
- lib/shortcodes/signup-form.php
- templates/head.php
- templates/header.php
CLS improvements
Close QualityUnit/web-issues#3232
> [3232] cls improvements

- base-scripts.php
- contactus-box.php
fix: contact form not loading, chatbot specific for directories
Close QualityUnit/web-issues#3246
Close QualityUnit/web-issues#3249
> fix: contact form not loading, chatbot specific for directories

- lib/shortcodes/signup-form.php
i fixed bug with including js file for the dorpdown on the trial signu up page
**Checklist**
> Fix bug on the trial signup form

- assets/scripts/static/crmCaptcha.js
- assets/scripts/static/crmForms.js
- lib/trial-signup/class-trial-signup.php
I added a check if there are more than 3 characters in the domains input
**Checklist**
Close QualityUnit/web-issues#3039
> [3039] Impossible to resubmit sign up form

- assets/styles/layouts/_PricingPrograms.scss
I added styles for flexible margins for the normal price and discount price
**Checklist**
Close QualityUnit/web-issues#3713
> [3713] Stop timer Discontinue Discount Pricing for LiveAgent

- assets/styles/components/IconTabs.scss
Change visual view for range text on /live-chat-software/ page.
- Go to page /live-chat-software/ and check view range in tab: "Cost effectiveness"
**Checklist**
Close QualityUnit/web-issues#3323
> [3323] - fix: change visual view for range text

- lib/shortcodes/signup-form-free.php
Change visual view for h2 by design
- Go to http://www.liveagent.com/free-knowledge-base-software/ and
https://www.liveagent.com/free-call-center-software/ and check visual view h2
**Checklist**
Close QualityUnit/web-issues#3303
> [3303] - fix: change visual view for h2 by design

- assets/styles/components/_HeroHeadlineBanner.scss
- lib/shortcodes/good-hands.php
- templates/header.php
Update styles for buttons on homepage and
added CTA
- Go to homepage and check visual view of buttons
**Checklist**
Close QualityUnit/web-issues#3307
> [3307] - fix: update styles for buttons on homepage

- assets/styles/common/_global.scss
Fixing cases where media blocks are used
Close QualityUnit/web-issues#3237
> [3237] fix: icons sizes

- lib/metaboxes/signup-sidebar.php
- lib/shortcodes/signup-sidebar.php
I changed shortcode `signup_sidebar`. I added support for chose what form you need show.
**Checklist**
Close QualityUnit/web-issues#3332
> [3332] Replacement of Free Plan/Account widget by Free Trial widget

- lib/shortcodes/alternatives.php
Fix alternatives shortcode (changed adding class in svg)
- Go to page /smartsupp-alternative/ and scroll to section 
"Compare us with other solutions" and check visual items of section
**Checklist**
Close QualityUnit/web-issues#3334
> [3334] - fix: changed adding class in svg

- assets/styles/components/compactHeader.scss
Reduced height on top scroll panel on single articles
- Go to single articles on Blog, scroll page and check visual
view of scroll top panel (padding-top, padding-bottom - 1em)
**Checklist**
Close QualityUnit/web-issues#3338
> [3338] - fix: reduced height on top scroll panel on single articles

- ai-chat-button.php
- assets/styles/components/_ContactUs.scss
- base-scripts.php
- contactus-box.php
I replaced flowhunt script for chatbot with new LA widget
**Checklist**
Close QualityUnit/web-issues#3343
> [3343] Request for replacement of chatbot button in contact multiwidget on LiveAgent.com

- ai-chat-button.php
- base-scripts.php
- chat-button.php
- contactus-box.php
- i rewrite the text in multiwidget "chat with agent" to "chat"
- removed Ai chatbot from multiwidget
- added new chat to pricinge and removed multiwidget
- fixed duplicate script after click on the button for accept cookies
**Checklist**
Close QualityUnit/web-issues#3349
> [3349] Chat & chatbot widget adjustments on the website

- base-scripts.php
Added script for CrozDesk Conversion Tracking
- Go to trial page and check working CrozDesk Conversion Tracking
**Checklist**
Close QualityUnit/web-issues#3348
> [3348] - feat: added script for CrozDesk Conversion Tracking

- assets/i18n/trial_banner/ar.json
- assets/i18n/trial_banner/bg.json
- assets/i18n/trial_banner/cs.json
- assets/i18n/trial_banner/da.json
- assets/i18n/trial_banner/de.json
- assets/i18n/trial_banner/el.json
- assets/i18n/trial_banner/en.json
- assets/i18n/trial_banner/es.json
- assets/i18n/trial_banner/et.json
- assets/i18n/trial_banner/fi.json
- assets/i18n/trial_banner/fr.json
- assets/i18n/trial_banner/hr.json
- assets/i18n/trial_banner/hu.json
- assets/i18n/trial_banner/it.json
- assets/i18n/trial_banner/ja.json
- assets/i18n/trial_banner/lt.json
- assets/i18n/trial_banner/lv.json
- assets/i18n/trial_banner/nl.json
- assets/i18n/trial_banner/no.json
- assets/i18n/trial_banner/pl.json
- assets/i18n/trial_banner/pt-br.json
- assets/i18n/trial_banner/ro.json
- assets/i18n/trial_banner/ru.json
- assets/i18n/trial_banner/sk.json
- assets/i18n/trial_banner/sl.json
- assets/i18n/trial_banner/sv.json
- assets/i18n/trial_banner/tl.json
- assets/i18n/trial_banner/vi.json
- assets/i18n/trial_banner/zh-hans.json
Changed 14 to 30 on trial banner and translated for trial banner
- Go to /industry/ page, scroll down and check banner, need 30 free trial
**Checklist**
Close QualityUnit/web-issues#3734
> [3734] - fix: changed 14 to 30 on trial banner and translated for trial banner

- assets/styles/layouts/Header.scss
- templates/header.php
Changed styles for free trial button on mobile menu and
added demo button on header top section
- Go to mobile version and check visual view demo button and
free trial button inside of menu 
**Checklist**
Close QualityUnit/web-issues#3347
> [3347] - demo trial buttons on mobile devices

- assets/styles/common/_elementor.scss
- assets/styles/common/_variables.scss
- assets/styles/components/Block.scss
- assets/styles/components/_HorizontalTabs.scss
- assets/styles/elements/_Typography.scss
Unified styles for h2 (large-heading)
- Go to all pages of sites and check correct view for
h2 tags with large-heading class
**Checklist**
Close QualityUnit/web-issues#3339
> [3339] - unify h2 font size

- assets/scripts/static/crmInstaller.js
- assets/styles/pages/ThankYou.scss
- lib/trial-signup/class-trial-signup.php
-- used new API endpoint to get installation progress,
-- after successfull installation displayed Log In button with counter while login link is valid
-- when crm api do not return `login_token`, displayed is only message to log in via email
Close QualityUnit/web-issues#3354
> I3354 trial installation

- assets/scripts/static/crmInstaller.js
- assets/styles/pages/ThankYou.scss
fixed form which move user to liveagent after successful account installation
Close QualityUnit/web-issues#3357
> I3357 submit form

- assets/scripts/static/crmInstaller.js
Changed condition for function what created button for redirect after finish progress. CRM now don't send old parameter `login_token` only `login_url`
**Checklist**
> Changed condition for function what make button for redirect to app

- functions/check-parent-child-slug.php
added condition for function
**Checklist**
> Fix function check_parent_child_slug

- assets/i18n/trial_banner/en.json
- assets/styles/elements/_FilterMenu.scss
- templates/content-archive-ms_success-stories.php
- Revert commit of Jozef for filters because all other dropdowns was broken.
- Fixed some texts 
**Checklist**
> Fixed styles for filters and dropdowns and some content fixes

- elementor.php
- functions/metaboxes.php
- lib/metaboxes/show-related-articles.php
Added now metabox for show and hide related articles on the postype page and added conditional display logic.
1. Edit any page and toggle the "Enable Related Posts Section" option in the metabox.
2. check page if metabox work properly
> Added related articles metabox and conditional display logic

- assets/styles/layouts/_PricingPrograms.scss
Changes styles for PromoBanners on Pricing page
- Go to pricing page and check PromoBanners "Deal for Startups"
**Checklist**
Close QualityUnit/la-marketing#3787
> [3787] - optimization pricing page

- lib/metaboxes/landing-ppc.php
preselected image list for header
Close QualityUnit/web-issues#3382
> [3382] feat: preselected image list for header

- lib/shortcodes/signup-form-landingppc.php
- lib/shortcodes/signup-form.php
- template-trial-redesign.php
- templates/content-archive-ms_alternatives.php
Changed text in trial page and removed text "Free trial for 30 days with a company email"
- Go to trail page and check text/tooltip on form
**Checklist**
Close QualityUnit/web-issues#3378
> [3378] - fix: changed text in trial page

- landing-ppc.php
- lib/metaboxes/landing-ppc.php
Fix to show images in page editor
Close QualityUnit/web-issues#3382
> [3382] fix: showing header images in page editor

- assets/styles/components/BlockCoupon.scss
- assets/styles/shortcodes/Countdown.scss
customized banner for spring sale
**Checklist**
Close QualityUnit/web-issues#3791
> [3791] Spring Deal 2025 Promotion

- landing-ppc.php
- lib/metaboxes/landing-ppc.php
alt support for image, youtube id explanation
Close QualityUnit/web-issues#3382
> [3382] fix: alt support for image, youtube id explanation

- landing-ppc.php
- lib/metaboxes/landing-ppc.php
Editable header button
Close QualityUnit/la-marketing#3709
> [3709] landingppc button

- assets/styles/components/BlockCoupon.scss
- assets/styles/shortcodes/Countdown.scss
Changed styles for coupon banner
- Go to /pricing/ page and check visual view
coupon banner on all devices
**Checklist**
Close QualityUnit/web-issues#3387
> [3387] - fix: changed styles for coupon banner

- landing-ppc.php
- lib/shortcodes/good-hands-new.php
- lib/shortcodes/signup-form-landingppc.php
> fix: texts on the landing pages

- assets/styles/layouts/_PricingPrograms.scss
Changed hover styles for buttons
- Go to /pricing/ and check hover effect in buttons of "LiveAgent Pricing" section
**Checklist**
Close QualityUnit/web-issues#3787
> [3787] - fix: changed hover styles for buttons

- assets/styles/components/compactHeader.scss
- assets/styles/layouts/_Blog.scss
- functions/metaboxes.php
- lib/custom-blocks/compact-header.php
- lib/metaboxes/blog.php
- templates/content-archive.php
Updated featured image, text on blog articles with label "monthly updated"
Created metaboxes with checkbox, title and text for label on blog articles
Added text on featured image on "top posts", archive and single posts on blog articles
- Go to /blog/ and check new featured image with text for "monthly
updated" articles
**Checklist**
Close QualityUnit/la-marketing#3785
> [3785] - universal cover for update blog article

- assets/styles/layouts/tests/RequestDemo.scss
Changed styles for form in demo page
- Go to LA /demo/ page and check visual view button of form
**Checklist**
Close QualityUnit/web-issues#3397
> [3397] - fix: changed styles for form in demo page

- assets/styles/layouts/tests/RequestDemo.scss
Changed height for demo form
- Go to demo pages all languages and check visual view of form
**Checklist**
Close QualityUnit/web-issues#3397
> [3397] - fix: changed height for demo form

- assets/styles/components/AiChatbotSection.scss
fixed styles for ai chatbot section on mobile
> Fix ai chatbot section on mobile

- assets/styles/components/BlockVideo.scss
hide images inside BlockVideo wrapper if element is img
> hide images inside BlockVideo wrapper if its element img

- assets/styles/layouts/LandingPPC.scss
- template-trial-redesign.php
Changed text on trial page and fixed style for image on mobile PPC template
**Checklist**
Close QualityUnit/web-issues#3862
> [3862] - feat: changed text on trial page

- assets/scripts/custom/blogLazyLoad.js
- lib/rest-api/get-blog-posts.php
- templates/content-archive.php
Fixed duplicate articles of blog and added for articles after scrolling updated month label
- Go to /blog/ and check articles (shouldn't to be duplicate) and if we have articles with
update month label, check these label in all articles of list
**Checklist**
Close QualityUnit/web-issues#3408
> [3408] - fix: fixed duplicate articles of blog

- assets/styles/shortcodes/BlockPricing.scss
- lib/shortcodes/block-pricing.php
Changed "block pricing" shortcode (removed free plan)
- Go to /live-chat-software/ page and check pricing section
(should be three plan without "free")
**Checklist**
Close QualityUnit/marketing#3842
> [3842] - feat: changed "block pricing" shortcode (removed free plan)

- assets/styles/common/_variables.scss
- assets/styles/components/Boxes.scss
- assets/styles/components/_Newsletter.scss
- assets/styles/components/_SignupSidebar.scss
- assets/styles/elements/_Button.scss
- assets/styles/elements/_LabelTag.scss
- assets/styles/layouts/Header.scss
- assets/styles/layouts/_ComparePlansNew.scss
- assets/styles/layouts/_PricingPrograms.scss
- lib/shortcodes/newsletter-form.php
- templates/footer.php
- templates/header.php
Changed buttons design 
Go to home page of liveagent and check buttons colors
**Checklist**
Close QualityUnit/marketing#3859
> [3859] Implement new buttons based on data from A/B test

- assets/styles/components/_Login.scss
- assets/styles/layouts/Header.scss
- assets/styles/layouts/_ComparePlansNew.scss
Small design fixes in header and pricing page
**Checklist**
> Small design fixes in header and pricing page

- assets/styles/layouts/Header.scss
- templates/header.php
Replaced demo button with trial in header on mobile and fix some styles
**Checklist**
> Replace demo button with trial in header on mobile

- assets/styles/components/_GoodHands.scss
- assets/styles/shortcodes/BlockBadges.scss
Changed styles good hangs and badges sections on tablet and mobile devices
- Go to home page and check visual view good hands and badge sections
on tablet and mobile devices
**Checklist**
Close QualityUnit/web-issues#3411
> [3411] - fix: changed styles good hangs and badges sections

- assets/styles/layouts/LandingPPC.scss
- landing-ppc.php
Fixed small styles and removed duplicate block
- Go to landing ppc page (e.g. /landing/landing-ppc-preview-page/) and check new design
**Checklist**
Close QualityUnit/marketing#3860
> [3860] - fix: fixed small styles and removed duplicate block

- assets/scripts/static/crmInstaller.js
Go on trial page and fill fomrular and send. Then you have to see capterra script in DOM
**Checklist**
Close QualityUnit/web-issues#3410
> feat: replaced old capterra script with new

- assets/styles/elements/_Button.scss
- assets/styles/layouts/_ComparePlansNew.scss
few small design changes
**Checklist**
Close QualityUnit/marketing#3859
> [3859] Implement new buttons based on data from A/B test - fixing small design changes

- assets/scripts/static/crmInstaller.js
I replaced reddit script for tracking after submit trial button
**Checklist**
> feat: replaced reddit script for tracking

- assets/scripts/static/crmInstaller.js
I added linkedin tracing script to thank you page
**Checklist**
Close QualityUnit/marketing#3888
> [3888] Added linkedin tracing script to thank you page

- assets/scripts/app/app.js
I added condition for control if menu item is link.
**Checklist**
Close QualityUnit/web-issues#3415
> [3415] Fix header function waht amkes consol error on trial page on dev liveagent

- assets/scripts/static/crmInstaller.js
I refactor how to include scripts in to thankyou page via CRM installer
**Checklist**
Close QualityUnit/web-issues#3410
> [3410] Refactor tracker injection into modular handler methods

- templates/content-archive-ms_features.php
Changed description text for features section
- Go to /features/ and check text
**Checklist**
Close QualityUnit/marketing#3907
> [3907] - fix: changed description text for features section

- assets/scripts/static/crmInstaller.js
I removed alt text from google tracking script
**Checklist**
> fix: removed alt text from tracking script

- assets/styles/layouts/_Post.scss
I only delete padding for that buttons
> Fix broken design for buttons

- assets/styles/elements/_LabelTag.scss
- assets/styles/layouts/Header.scss
- assets/styles/pages/TrialRedesign.scss
- template-trial-redesign.php
I added label to header and trial page
Check header on LA and then go to trial page. You need see label `limited offer`
**Checklist**
Close QualityUnit/web-issues#3938
> [3938] Communication of the limited prices on trial page and HP

- assets/scripts/static/crmInstaller.js
I created reddit tracker as JS function for correct working
**Checklist**
> created reddit tracking as js function for correct working
