QualityUnit/liveagent-theme

assets/scripts/custom/IconTabs.js

Javascript addon to force animation restart on tabs clicking
**Checklist**
Close QualityUnit/web-issues#416

[416] Javascript addon to force animation restart on tabs clicking

---

assets/styles/components/_Block.scss

Fix for ignoring elementor Spacer widget
**Checklist**

Fix for ignoring elementor Spacer widget

---

assets/styles/elements/_Button.scss
assets/styles/layouts/_Header.scss
templates/header.php

Added demo button next to free trial, added wrapping div around free trial for better responsivity
We need to remove former demo button from navigation menu (both normal and mobile) in WP.
**Checklist**
Close QualityUnit/web-issues#479

[479] feat: Changed demo button

---

assets/styles/elements/_Button.scss

In relation to redesign of Demo button in main navigation, in few languages it was too wide, so I have applied smaller padding on the button.
**Checklist**
**Note**
after closing this PR we need to delete hotfix for these languages in WP

[479] fix: changed padding of Demo button

---

assets/scripts/app/custom_lightbox_youtube.js
assets/styles/components/_BlockVideo.scss
assets/styles/elements/_YoutubeLoader.scss
templates/head.php

Allowing click on whole play button in vertical video box
Go to https://www.liveagent.com/ticketing-software/ and check if clicking on orange Play buttons is working correctly – it should open modal Youtube box regardless of where you click on it. Clicking on image should work too. It shouldn't cause to load video twice (creating two sound streams running)
**Checklist**
Close QualityUnit/web-issues#503

[503] fix: allowing click on whole play button in vertical video box

---

assets/styles/elements/_Button.scss
assets/styles/layouts/_Header.scss
templates/header.php

Changed demo button to its original state: 
- removed as standalone button in header menu
- removed styling for demo button
- added back to header navigation as menu item
**Additional note**
After implementing its needed to add Demo into menu in WP.
**Checklist**
Close QualityUnit/web-issues#514

[514] feat: reverted demo button to its original state

---

assets/scripts/custom/pricing.js

changed scroll event to intersection observer to avoid jumping icon
When you click on Show All Features in pricing, icons in a table header should no longer „jump“ after scrolling to position
**Checklist**
Close QualityUnit/web-issues#521

[521] fix: changed scroll event to intersection observer to avoid jumping icon

---

assets/styles/components/_ExtraFaq.scss

Changed color of links in FAQ section from default to primary
Check links color on page (primary FAQ section on demo page)
**Checklist**
Close QualityUnit/web-issues#606

fix: faq links color from default to primary color

---

lib/shortcodes/block-pricing.php

Hotfix for "compare-plans" button. Changed link
**Checklist**

fix: fixed link on compare-plans button

---

lib/setup.php

disable force moving of js to footer due to many errors
**Checklist**

fix: disable force moving js to footer

---

assets/scripts/custom/slider.js
lib/shortcodes/customers-bubble.php
lib/shortcodes/slider-testimonials-custom.php
lib/shortcodes/slider-testimonials.php
lib/shortcodes/small-photo-slider.php
lib/shortcodes/voip-partners.php

Sliders images loading at once if slider is in viewport.
This fixes Google screaming about long loading times when images in sliders were lazy loaded right before showing up on next slide move.
**Checklist**

[586] fix: sliders images loading at once if slider is in viewport

---

assets/styles/components/_Block.scss

Value boxes are now full width on mobile resolution
Removed background on each box for tablet resolution
Check the design on [this](http://liveagent.local) page.
**Checklist**
Close QualityUnit/web-issues#571

[571] style: fix for value boxes on mobile and tablet viewport

---

assets/styles/layouts/_BlogPost.scss
assets/styles/layouts/_Gutenberg.scss
functions/content-filters.php
lib/widgets/qu-howtos/src/scss/_howto.scss

Removed dropcap generator, moved to :first-letter css style
**Checklist**
Close QualityUnit/web-issues#655

[655] fix: removed dropcap generator, moved to :first-letter css style

---

apps/typing-test/src/style.css
lib/shortcodes/good-hands.php
lib/shortcodes/gutenberg-awards.php
lib/shortcodes/gutenberg-reference.php
lib/shortcodes/gutenberg-reviews.php
lib/shortcodes/reviews.php
template-academy-header.php
template-blog-header.php
template-demo.php
template-free-account.php
template-trial-redesign.php
template-trial.php
templates/head.php

Change old CDN to WWW urls. `cdn.liveagent.com` is no more supported.
**Checklist**

fix: change old cdn to www cdns url

---

assets/styles/components/_BlockPricing.scss

Changed font weight on tags in context of https://github.com/QualityUnit/web-issues/issues/494 where was an error in design
**Checklist**

fix: changed font weight on pricing tags

---

assets/scripts/custom/sidebar_toc.js
lib/shortcodes/login.php
lib/shortcodes/signup-form-free.php
lib/shortcodes/signup-form.php
lib/shortcodes/signup-sidebar.php

fix: removing lazyload from signup critical scripts, fixing loading of scripts by sidebar
**Checklist**
Close QualityUnit/web-issues#880

[880] fix: removing lazyload from signup critical scripts

---

functions/content-filters.php

- remove schema.org fix
_Note: The function is generating tons of PHP Warning with newest Yoast SEO_ `PHP Warning: Invalid argument supplied for foreach() in /var/www/html/web/app/plugins/wordpress-seo/src/generators/schema-generator.php on line 231`
**Checklist**
Close QualityUnit/web-issues#734

[734] fix: remove schema.org fix

---

templates/content-archive-ms_research.php
templates/content-single-ms_research.php

Research posts/categories php error fix by removing one WP_QUERY parameter
**Checklist**
Close QualityUnit/web-issues#918

[918] fix: research posts/categories php error

---

template-academy-header.php
template-blog-header.php
template-trial-redesign.php

Added "urlslab-min-width" classes for hide images on mobile (mostly in hero sections).
Check image loading on responsive.
**Checklist**
Close QualityUnit/web-issues#953

[953] hide images on mobile with urlslab class

---

functions/content-filters.php

remove trailing slash for pdf files
verify here then https://admin.liveagent.com/gdpr/
**Checklist**

fix: remove trailing slash for pdf files

---

assets/styles/components/_Block.scss

Removed vertical space for images on mobile in blocks with aside
Check vertical space for images on mobile in blocks with aside
**Checklist**
Close QualityUnit/web-issues#969

[969] Removed vertical space for images on mobile in blocks with aside

---

composer.lock
functions/content-filters.php
lib/widgets/qu-reviews/reviews.php
templates/footer.php

Adding theme versioning for icons.svg fragment calls across the template
**Checklist**

fix: adding theme versioning for icons.svg

---

lib/assets.php
template-academy-header.php
template-blog-header.php

move elementor-custom CSS to header to avoid incredible big CLS
**Checklist**

[995] fix: move elementor-custom to header

---

templates/content-archive-ms_reviews-sorting.php
templates/content-archive-ms_reviews.php

subtitle header only if filled in, removed reviews word in header
**Checklist**
Close QualityUnit/web-issues#1090

[1090] fix: subtitle header only if filled in, removed reviews word in header

---

assets/styles/shortcodes/BlockPricing.scss

Fixed labels in pricing block for correct display of tooltip icon (after html markup change in elementor).
New elementor markup:
`<div class="pricing__tags">`
`    <div class="pricing__tags__label">7 or 30 days free trial&nbsp;`
`        <div class="Tooltip">`
`            <span class="fontello-info"></span>`
`            <span class="Tooltip__text">Free trial for 7 days with a free email, or 30 days with a company email</span>`
`        </div>`
`    </div>`
`    <div class="pricing__tags__label">No Credit Card required</div>`
`    <div class="pricing__tags__label">and many more</div>`
`</div>`
Check tooltip icons in pricing blocks.
**Checklist**
Close QualityUnit/la-marketing#2455

[2455] Tooltips in block pricing blocks

---

lib/shortcodes/signup-form.php

Hide message in signup form when an email address which we don't recognize as free is entered.
Check signup form on trial page.
**Checklist**
Close QualityUnit/web-issues#1122

[1122] Toggle signup form free trial message

---

functions/get-posts.php
lib/metaboxes/features.php

Fixing handling all integrations only in Features categories as using global was causing demanding queries to be called (and memory limit bugs)
Close QualityUnit/web-issues#2265

[2265] fix: getting integrations only in features category

---

assets/styles/components/SignupSidebar.scss
lib/assets.php
template-blog-header.php

I changed the import of styles from body to head so that the elements have styles immediately and the content does not bounce
**Checklist**
Close QualityUnit/web-issues#2588

[2588] Rearrange the order in which CSS files load to minimise CLS 

---

templates/content-single-ms_videos.php

I added only urlslab FAQ shortcode to single page of videos
**Checklist**
Close QualityUnit/web-issues#2624

[2624] FAQs added through urlslab are not showing in "Videos" on LA

---

assets/styles/components/AnnouncementBar.scss

I removed paddings on mobile devices and add correct padding to app container if is announcement bar active on the desktop.
**Checklist**
Close QualityUnit/web-issues#2629

[2629] The pricing deal banner is not fully visible

---

templates/content-single-ms_glossary.php

I added bg style to php for block discover expert element on glossary 
**Checklist**
Close QualityUnit/web-issues#2783

[2783] Expert's note element missing backround

---

lib/shortcodes/discover.php
templates/content-single-ms_glossary.php

i fixed urls for glossary single and discover shortcode. Just remove '' form code
**Checklist**
Close QualityUnit/web-issues#2742

[2742] Fix urls for glossary single and discover shortcode

---

assets/styles/components/Signup.scss
assets/styles/shortcodes/IntroductionVideos.scss
lib/shortcodes/signup-form-free.php
lib/shortcodes/signup-form-redeemcode.php
lib/shortcodes/signup-form-simple.php
lib/shortcodes/signup-form.php
lib/shortcodes/signup-sidebar.php

Fixed css for introduction tabs in signup installation process.
Fixed styling issues for inputs with removed default `type="text"` attr by urlslab plugin.

Signup small css fixes + fix for urlslab inputs html optimization

---

assets/styles/components/Signup.scss

I added background color for tooltip icon
**Checklist**
Close QualityUnit/web-issues#2844

[2844] Missing background behind input info icon

---

assets/scripts/static/crmInstaller.js
lib/trial-signup/class-trial-signup.php

php sessions no more used to pass data between `/trial` and `/thank-you` pages.
Data stored as cookies array after form submission and immediately removed after redirect to `/thank-you` when cookie is read before page load.
For our crm installation js are data from cookie handled on server before load.
Close QualityUnit/web-issues#2920

Trial signup removed sessions usage

---

assets/scripts/static/crmForms.js

Disallowed usage of `%` in email field.
Name field was already disallowed in name field. 
Close QualityUnit/web-issues#2969

fix: disallow percentage character in email

---

templates/content-single.php

I added condition for categories on the content single template
**Checklist**
Close QualityUnit/web-issues#3003

[3003] PHP Warning: foreach() argument must be of type array|object

---

assets/styles/shortcodes/IntroductionVideos.scss

I removed `content:""` css from img element because `content:""` is only for pseudoelements as before and after
**Checklist**
Close QualityUnit/web-issues#3072

[3072] Missing icons in setup interactive element 

---

functions.php
functions/urlslab-related-posts.php
template-academy-header.php
template-academy.php
template-blog-header.php
template-blog.php
templates/content-single-ms_academy.php
templates/content-single-ms_checklists.php
templates/content-single-ms_features.php
templates/content-single-ms_glossary.php
templates/content-single-ms_integrations.php
templates/content-single-ms_reviews.php
templates/content-single-ms_templates.php
templates/content-single-ms_videos.php
templates/content-single.php

I created a function to display related articles via a shortcode from urlslab and added a condition to display the title only if the urlslab shortcode displays something and also added a url parameter to the shortcode.  And i replaced old code in the all templates
**Checklist**
Close QualityUnit/web-issues#3135

[3135] Hide title "Related articles" if empty

---

assets/styles/components/_TrialStickyButton.scss

I rewrote the styles for the sticky trial button to be more flexible for longer text in the button because it was affecting the contact us button
**Checklist**
Close QualityUnit/web-issues#3176

[3176] Title of button too long

---

assets/styles/elements/_Typography.scss

I added a condition in css for the class tag. The class tag was in the body element because the page name is "Tag" and it affected the page styles
**Checklist**
Close QualityUnit/web-issues#3038

[3038] Different font on a page

---

assets/scripts/custom/sidebar_items_slider.js

I have removed the feature that is causing this warning. Because the sidebar scroller now has links and redirects to other checklists, no scrolling to the section for which the `loadImg` function was created
**Checklist**
Close QualityUnit/web-issues#3258

[3258] Fix code scanning alert - DOM text reinterpreted as HTML

---

lib/shortcodes/web-calc.php

I removed code what adding parameter `#showWebCalcGenerator` to url. A then was visible shortcode generator. It was only for testing i think
**Checklist**
Close QualityUnit/web-issues#3263

[3263] calculator is not working

---

assets/scripts/custom/sidebar_toc.js
functions/sidebar-toc.php

Fix for the add_id_to_h2 function, which now:
- Skips headings that already have an ID
- Does not add an ID to headings without text
And added logic to remove 'scrolled' class from sidebarTOC and signupSidebar when scrolling back up and elements move out of view.
**Checklist**
Close QualityUnit/web-issues#3291

[3291] Id attribute for H tags with ID

---

assets/scripts/custom/countdown.js

1.	Safari compatibility issue: 
Safari could not parse the data-endtime attribute due to non-ISO 8601 date format, resulting in Invalid Date.
2.	Error when target elements were missing:
If countdown elements ([data-days], [data-hours], etc.) were absent, it caused runtime errors.
3.	Unnecessary interval execution:
The timer continued running even after the countdown had ended, wasting resources.
4.	Complex and redundant time calculation logic:
Time calculation involved unnecessary steps, reducing readability and increasing error potential.
**Checklist**

fix: countdown in the safari

---

assets/scripts/app/app.js

We had JS code that worked so that if there was a trial form in the content, then in all buttons that were for creating a trial account, it would cancel the default linking and rewrite it to an anchor link to the form on that page. So I added support for disabling this function if we want a classic button.
**Checklist**

Added support for disabling anchor buttons

---

assets/styles/components/IconTabs.scss

Changed conflict of styles for range text
- Go to page /live-chat-software/ and check
"Cost effectiveness" tab (text on range block)
**Checklist**
Close QualityUnit/web-issues#3323

[3323] - fix: changed conflict of styles for range text

---

assets/styles/layouts/Header.scss
templates/header.php

Show demo button instead of free trial demo on header top
section on mobile devices
- Go to any page with header and check on mobile device need visible
demo button on header top section
**Checklist**
Close QualityUnit/web-issues#3347

[3347] - fix: show demo button instead of free trial on header

---

base-scripts.php
functions.php
functions/check-parent-child-slug.php

Changed "contact us" multi-widget to chatbot button for
next pages/subpages:
https://www.liveagent.com/business/
https://www.liveagent.com/industry/
https://www.liveagent.com/checklists/
https://www.liveagent.com/reviews/
https://www.liveagent.com/awards/
- Go to above pages and check chatbot button instead contact us" multi-widget
**Checklist**
Close QualityUnit/la-marketing#3703

[3703] - fix: changed "contact us" multi-widget to chatbot button

---

assets/styles/common/_elementor.scss
assets/styles/components/_HeroHeadlineBanner.scss
assets/styles/components/_HorizontalTabs.scss

Changed h2 (large-heading) and few styles on tablet and mobile devices
- Go to front-page and check visual view h2 (large-heading) on mobile and
check hero section on tablet and mobile (buttons need to be with gap and
without margin-left and aligned by center on mobile.
**Checklist**
Close QualityUnit/web-issues#3358

[3358] - huge font size h2 on mobile

---

apps/web-calc/src/assets/style/common/_variables.scss
apps/web-calc/src/assets/style/elements/_Block.scss
apps/web-calc/src/assets/style/elements/_Feature.scss
apps/web-calc/src/assets/style/elements/_Select.scss

Changed styles that override box-shadow
- Go to page with web-calc widget e.g. /zendesk-alternative/ and
check that "Start Free Trial" form has correct-box-shadow
**Checklist**
Close QualityUnit/web-issues#3355

[3355] - fix: changed styles that override box-shadow

---

assets/styles/pages/TrialRedesign.scss
template-redeem-code.php
template-trial-redesign.php

Removed captera and g2 badges on trial page
- Go to trial page and check (captera and G2 don't need to be on page)
**Checklist**
Close QualityUnit/web-issues#3376

[3376] - fix: removed captera and g2 badges on trial page

---

landing-ppc.php

i delete empty space in `href` attribut because some space in code add to link `href="/trial/%09%09"`
**Checklist**
Close QualityUnit/la-marketing#3709

fix: delete empty space in link

---

assets/styles/components/HeroHeadlineHome.scss

Added gap between labels and title and text of hero section
- Go to /industry/ page and check hero section, should be
gap between labels and left content
**Checklist**
Close QualityUnit/web-issues#3388

[3388] - overlaping elements industry page

---

landing-ppc.php
lib/metaboxes/landing-ppc.php

I added metabox for disabling internal linking from urlslab. 
Open any landing page, check new metabox "Internal Linking". 
if you chose disable linking then in code added class for disabling `urlslab-skip-keywords`
**Checklist**
Close QualityUnit/marketing#3827

[3827] The internal links duplicity removal on LPs for PPC campaigns 

---

functions.php
functions/disable-speculative-loading.php

Added a new function to disable speculative loading using the `wp_speculation_rules_configuration` filter. This prevents the Speculation Rules API from preloading resources, improving control over resource loading behavior.
Go to the LA homepage. Open dev tools and in elements find speculative script. You can't find him.
**Checklist**

feat: disable speculative loading via wordpress filter

---

assets/styles/elements/_PostTypography.scss

Changed aligned on success stories wider sections and reduced margins for it
- Go to /use-case-scenarios/matchaflix/ and check aligned text in updated containers
**Checklist**
Close QualityUnit/marketing#3809

[3809] - fix: changed aligned on success stories

---

lib/shortcodes/request-for-proposal-form.php
lib/shortcodes/signup-form-landingppc.php
lib/shortcodes/signup-form.php
lib/shortcodes/signup-sidebar.php
template-redeem-code.php
template-trial-redesign.php
templates/content-archive-ms_alternatives.php
templates/footer.php

Changed grammatical errors  in the "Start free trial" widget
- Go to trial page or e.g. /help-desk-software/ and check texts and button
- Should be "Experience working with LiveAgent for free with our 30-day free trial.", "Start a free trial", "No credit card required" and button "30-day free trial"
**Checklist**
Close issue https://github.com/QualityUnit/web-issues/issues/3587

fix: changed text for trial page
